### PR TITLE
Created my own background music and added it && Added music to tile marina

### PR DESCRIPTION
**Pull request by samyakbvs**
Background music name Drumplo

http://rawgit.com/samyakbvs/labyrinth/master/index.html

### CODE REVIEW

**Comment by samyakbvs** [comment]
The tile music is also created by me @niccokunzmann

**Comment by samyakbvs** [comment]
So I don't think any license is required for these files :)

**Comment by niccokunzmann** [comment]
@samyakbvs Thanks, I heard the Drumplo but I can not play the runnergarage. Can you check?
Also, currently the song is AGPL licensed. I hope this is your intention!

**Comment by samyakbvs** [comment]
What do you mean by AGPL licensed?

**Comment by samyakbvs** [comment]
@niccokunzmann

**Comment by samyakbvs** [comment]
and @niccokunzmann I think you were not able to listen Runnergarage bcs the Preview links don't get updated

**Pull request merged**
