### PR TITLE
Added a new level, Theme: Superheroes

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Added a theme, Superheroes
Collaboration of @arjunpandey2003 @saarthakchats @samyakbvs 
Please Judge on code basis. 
Moreover, since there was no level code in desert level added levelCode:3
Hope you like it!

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
Can you guys review and tell if all necessary files are added thanks :)

**Comment by saarthakchats** [comment]
@niccokunzmann 
Yes, me and @samyakbvs collaborated with @arjunpandey2003 for adding this level. Tell us what you think :D

**Comment by samyakbvs** [comment]
I also confirm that I have worked on this PR @niccokunzmann

**Comment by niccokunzmann** [comment]
Hi, first of all thanks for all the work you put in. There is one blocker I see: do you own the rights to the pictures you upload? Please provide the license of the heroes for every single hero.

**Comment by niccokunzmann** [comment]
Also, travis fails. Please fix this. It might work if you merge master.

**Comment by samyakbvs** [comment]
The images are taken from google @niccokunzmann How will we provide a license for it?

**Comment by saarthakchats** [comment]
@niccokunzmann 
Travis is failing for all PRs in entirety. Don't really know why

**Comment by naveentherocker** [comment]
@samyakbvs There is a tool in Google where you can sort out the Images with No Copyright Issues

**Comment by samyakbvs** [comment]
okay

**Comment by arjunpandey2003** [comment]
@niccokunzmann we are making a fresh new PR

**Pull request closed without merging**
