### PR TITLE
Added a new character-Wreck It Ralph

### LINKED ISSUE #965: Add a new character
### Description 

Ralph is from the movie Wreck It Ralph.This is the character I would like to add.

### Implementation Plan

- [x] Read the [documentation about adding characters].
- [x] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [x] Upload the character to the [characters folder].
- [x] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [x] The character is added to the menu to choose characters which is
  shown once the game starts.
- [x] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gui.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-941-fossasia-labyrinth.surge.sh

- Fixes #965

### Screenshots, Location of Changes, Path to Tile

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by NishithP2004** [comment]
@YashKumarVerma I have done as requested

**Comment by NishithP2004** [comment]
@YashKumarVerma I have changed the character .

**Comment by NishithP2004** [comment]
@YashKumarVerma Please review this I have improvised it .

**Comment by NishithP2004** [comment]
@pranav1698 I didn’t squash the commits because it took a long time to clone and the character is of the correct size as mentioned in the task.i.e 55x60 px

**Comment by pranav1698** [comment]
@NishithP2004 you still have to squash your commits their are way too many 
There are many sources on the internet if you search that will help you in squashing, it will not take much time I am doing it frequently

**Comment by NishithP2004** [comment]
@pranav1698 Thanks for the suggestion, I will do as suggested.

**Comment by pranav1698** [comment]
screenshot from 2018-11-29 17-32-40
screenshot from 2018-11-29 17-33-11
Mario appears very small in comparison

**Comment by pranav1698** [comment]
With squashing!!

**Comment by NishithP2004** [comment]
@pranav1698 no with making it big

**Comment by pranav1698** [comment]
You can use any svg editors; There are many editors online

**Comment by pranav1698** [comment]
I think by using a svg image editor

**Comment by abishekvashok** [comment]
Still small

**Comment by NishithP2004** [comment]
@abishekvashok I have put the size as mentioned in README file I.e.55x60 px.

**Comment by NishithP2004** [comment]
@abishekvashok can I put any measurement then?

**Comment by abishekvashok** [comment]
Hey, @RahulMetre03 was working on it

**Comment by NishithP2004** [comment]
@abishekvashok @YashKumarVerma could you please review this.

**Comment by NishithP2004** [comment]
@abishekvashok

**Comment by abishekvashok** [comment]
Any relevant issue? If you could open one, I could give an approve.

**Comment by NishithP2004** [comment]
@abishekvashok I have updated the PR and the issue is #965

**Comment by abishekvashok** [comment]
Seems like he's on the web, we better squahs and merge.

@NishitP2004 use git on the terminal pls.

**Comment by abishekvashok** [comment]
You did changes on the GitHub web editor.

**Comment by NishithP2004** [comment]
Sorry I had to close this as I was not able to squash all the the commits.

**Comment by NishithP2004** [comment]
I have created a new PR #969

**Pull request closed without merging**
