### PR TITLE
Added audio

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Added audio
http://rawgit.com/arjunpandey2003/labyrinth/master/index.html
Right Up
Gong sound, made use of API.
Deploy link is not updated please check tiles.js for the same, my file addition is right, please judge on basis of file changes

### CODE REVIEW

**Comment by abishekvashok** [comment]
I am able to hear em

**Comment by abishekvashok** [comment]
on the checkmate tile. See the sound icon at the titlebar. Maybe it takes sometime to load.
screenshot_20180108_213828

**Comment by niccokunzmann** [comment]
@arjunpandey2003 Thanks for your pull request. Please see #291 for the documentation and review it by looking if you can apply how to document the licensing of the files.

**Comment by arjunpandey2003** [comment]
I am making a fresh PR. With the license and everything

**Pull request closed without merging**
