### PR TITLE
Added new Tile Orange :D

### PR DESCRIPTION
**Pull request by Beta-King**
http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by Beta-King** [comment]
please review and merge :D @abishekvashok @samyakbvs @niccokunzmann !!

**Comment by Beta-King** [comment]
please review and merge :D @samyakbvs @abishekvashok @niccokunzmann !!

**Comment by kubami9** [comment]
@0x48piraj Could you check it again please? It works for me, preview link also displays it properly. Maybe it was still loading?
works

**Comment by Beta-King** [comment]
@kubami9 @0x48piraj , thanks :D

**Comment by Beta-King** [comment]
can we merge ?? :D

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
