### PR TITLE
Fixed #76.Changed to floor tile dimensions

### LINKED ISSUE #76: Make tile door.drawn a ground tile
### Expected results

When I walk throughthe labyrinth: 3xdown 2xright, 
I would like to walk on the drawn floor.

### Actual results

There is a rectangle which is not a floor.

### How to solve

Please make this floor tile a tile which is like the other floor tiles.

Idea: In Inkscape you can do the following to the https://github.com/fossasia/labyrinth/blob/master/tiles/rooms/floor/drawn.svg tile
1. rotate the tile by 45 degrees
2. make the height of the tile smaller so it fits like the other floor tiles.

Created as a result from #75

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes #76 
Made changes according to issue
It looks like this now:
screen shot 2017-12-31 at 4 04 28 pm

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
@niccokunzmann fixed your issue

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by arjunpandey2003** [comment]
Welcome!!

**Comment by niccokunzmann** [comment]
Would you like to play the game and see if you can find anything which needs improvement and create new issues?

By the way: You can add a link to your change in the pull request, so we can look at

**Comment by naveentherocker** [comment]
Thank You @arjunpandey2003 for Working on this Tile

**Pull request merged**
