### PR TITLE
Adds orchestra tile which requires a guitar

### PR DESCRIPTION
**Pull request by abishekvashok**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

Adds orchestra tile where you can enter with a guitar which can be found
in the guitarCase tile. After it's found you can do your first solo
perfomance in view of a large no: of spectators
, 

Live link: http://rawgit.com/abishekvashok/labyrinth/master/index.html

### Screenshots,
screenshot_20180112_184216
screenshot_20180112_184222

### CODE REVIEW

**Comment by abishekvashok** [comment]
@niccokunzmann @0x48piraj @YashKumarVerma @saarthakchats @Beta-King pls review

**Comment by abishekvashok** [comment]
@Beta-King thanks

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by abishekvashok** [comment]
Welcome

**Pull request merged**
