### PR TITLE
Fixes #277: Credits

### LINKED ISSUE #277: How to add a character
In the how to add character section it isn't mentioned that the character shouldn't be an image of a renowned personality and if you want to add then you should have a proof that you are allowed to use his/her image
Also for GCI students the character should be your own work it can't be an image copied from somewhere

Working on it!!

### PR DESCRIPTION
**Pull request by samyakbvs**
I added a new file which will has all the credits to the sources that have helped in contributing 

Fixes #277

### CODE REVIEW

**Comment by samyakbvs** [comment]
http://rawgit.com/samyakbvs/labyrinth/master/index.html

**Comment by samyakbvs** [comment]
The Credits link was appearing below the 'How to play' link but now it is in the navbar

**Comment by saarthakchats** [comment]
Please squash commits

**Comment by arjunpandey2003** [comment]
Hey @samyakbvs lets collaborate and we will improve the page. :)

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
