### PR TITLE
formatted level.js

### PR DESCRIPTION
**Pull request by YashKumarVerma**
ref #208

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Please view your file you contribute and search for `function Level(specification)` How often is this in the file? Can you post the links to the locations?

**Comment by YashKumarVerma** [comment]
@niccokunzmann  2 time on my edit. 2 times on current (fossasia repo)

**Comment by YashKumarVerma** [comment]
Line 10,68 on FOSSASIA repo
Line 8,68 on my repo

**Comment by niccokunzmann** [comment]
I see ... This is problematic. We need to change this. Would you like to work on this? You can include it with the formatting.

**Comment by niccokunzmann** [comment]
You will need to update your branch.

**Comment by niccokunzmann** [comment]
I did it in #217.

**Comment by niccokunzmann** [comment]
Would you like to resolve the merge conflicts?

**Pull request closed without merging**
