### PR TITLE
Pull Request #723: Simple and easy cleaning up of index.html

### PR DESCRIPTION
**Pull request by himanshuc3**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I will not merge this without motivation. There is no issue specified. This change makes it impossible to find out, why a line is written with git blame. By which written down rule is this a change which can be accepted?

**Comment by xeon-zolt** [comment]
@himanshuc3 the problem with this pull request is that you have not told what are the changes ( just check diff once its difficult to find out ) and why are those changes made what it solves

**Comment by niccokunzmann** [comment]
This is git blame: https://github.com/himanshuc3/labyrinth/blame/c899f226908b382e1bc0acf64f239a3db99bd103/index.html

**Comment by himanshuc3** [comment]
So what I understand you're trying to say is I've changed a lot of lines, which I've not. Here's what I've done:
- [x] Not deleted any code. Replaced old jquery library with the latest one pulled up from cdn.
- [x] Indented code
- [x] Moved some include up and down.

My main purpose here is to remove redundancy. It does not probably reflect here but I noticed some css files include the same file which is included in html files. I'm moving towards it. So, I've rearranged includes. What do you say?

**Comment by duttaditya18** [comment]
Okay, here is the preview link : https://rawgit.com/himanshuc3/labyrinth/Issue%23723/index.html

Good work!

**Comment by niccokunzmann** [comment]
Thanks for the pull request and reviews. I would like to provide more details in the future.

**Pull request merged**
