### PR TITLE
Added licensing 

### PR DESCRIPTION
**Pull request by saarthakchats**
Added licensing to soundtracks
Issue #346 
I and @samyakbvs have collaborated.

### CODE REVIEW

**Comment by saarthakchats** [comment]
@niccokunzmann Is this ready to be merged

**Comment by niccokunzmann** [comment]
@samyakbvs Please confirm that you collaborated.

**Comment by samyakbvs** [comment]
Yes @niccokunzmann I have collaborated, you can also see my commit at the top

**Comment by saarthakchats** [comment]
@niccokunzmann Thanks. https://codein.withgoogle.com/dashboard/task-instances/5907023508013056/
Is this ready to be approved then?

**Comment by niccokunzmann** [comment]
Thanks, indeed, this is fine!
You could copy the second part of the license and add the date of retrieval as they do not seem to version their license. Otherwise, if they change the link or the site goes down, we may need to remove the sounds as the license is not complete, just a thought, may not happen in the near future but in the years to come.

**Pull request merged**
