### PR TITLE
Added character - Witch

### PR DESCRIPTION
**Pull request by saarthakchats**
[Deploy](http://rawgit.com/saarthakchats/labyrinth/master/index.html)

### CODE REVIEW

**Comment by saarthakchats** [comment]
Thanks guys

**Comment by saarthakchats** [comment]
@niccokunzmann Is it ready to merge?

**Comment by niccokunzmann** [comment]
Thanks for the reviews!

**Comment by niccokunzmann** [comment]
And the pull request :)

**Pull request merged**
