### PR TITLE
Changed Sword.png to Sword.svg

### PR DESCRIPTION
**Pull request by saarthakchats**
Reduces game size

### CODE REVIEW

**Comment by saarthakchats** [comment]
@niccokunzmann 
As you suggested ;)

**Comment by niccokunzmann** [comment]
depends. Please look at the source: 
https://github.com/fossasia/labyrinth/blame/master/tiles/rooms/floor/redFloor.svg#L100
and your source:
https://github.com/fossasia/labyrinth/pull/516/files#diff-e2deb7342c828c1da7b5ae27930aeef9

If you copy the SVG content into the file, it gets smaller.
If you copy the PNG into the file, you increase the site by factor 8/6 because it is base64 encoded.

**Comment by saarthakchats** [comment]
@niccokunzmann 
Now?

**Comment by saarthakchats** [comment]
#515

**Comment by niccokunzmann** [comment]
@saarthakchats Please compare the file sizes yourself. I will merge if we know whether it is smaller.

**Comment by saarthakchats** [comment]
The size changed from 6.45 KB to 3.89 KB

**Comment by saarthakchats** [comment]
@niccokunzmann 
I think this can be merged now?

**Comment by niccokunzmann** [comment]
Cool, thanks!

**Pull request merged**
