### PR TITLE
Added my self-created music to a tile

### PR DESCRIPTION
**Pull request by saarthakchats**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].

### Changes done in this Pull Request
- Created sound track
- Created license file
- Added to folder
- Made JS Changes
[newtracker.wav.zip](https://github.com/fossasia/labyrinth/files/2534984/newtracker.wav.zip)

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by saarthakchats** [comment]
@YashKumarVerma 
As far as I remember, @niccokunzmann had told me to make a personalised license file last year. Let's wait for his review also 👍

**Comment by YashKumarVerma** [comment]
@saarthakchats that's the reason i approved the pr😎

**Comment by niccokunzmann** [comment]
I will merge it like this. Generally, a self-written license is not open and maybe not compatible. One should choose from the licenses which are GPL compatible. That would need to be documented, to provide it to all people in a uniform way.
If it is a problem in the future, we will remove the music files with custom licenses. Probably, it is no problem.

**Comment by abishekvashok** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/6395249380294656/

**Pull request merged**
