### PR TITLE
Fixes #167 : Menu Bar won't overlap the Game Interface

### LINKED ISSUE #167: Bug: Menu bar showing with game interface!
### Expected results
Correct this! 
labissue

### Actual results
Make menu bar separately.

## Would you like to work on this
I am and @naveentherocker working on this

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #167 

Problem Solved: Earlier the Menu Bar overlapped the Game when advances to more tile. Now it won't happen anymore.

Preview Link - http://rawgit.com/STEdirisuriya/labyrinth/master/index.html

Committed by @STEdirisuriya and @naveentherocker
Ping @niccokunzmann

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you pls check this
screenshot_20180105_221222

**Comment by niccokunzmann** [comment]
@naveentherocker Why is this preview link to someone else? http://rawgit.com/STEdirisuriya/labyrinth/master/index.html

**Comment by niccokunzmann** [comment]
Ah I understand... I should read what you wrote :)

**Comment by niccokunzmann** [comment]
I see you moved the inventory.

**Comment by STEdirisuriya** [comment]
@niccokunzmann thanks for merge

**Pull request merged**
