### PR TITLE
Fix Missing Wall for Blood Tile

### PR DESCRIPTION
**Pull request by AirWolfXD**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].

### Changes done in this Pull Request

- View my work at https://pr-801-fossasia-labyrinth.surge.sh

- Fixes missing wall

### The problem I want to solve or the facility I want to improve is/are

-Fix the missing wall problem for the blood tile

### My steps to solve it

-Change wall svg file

### Screenshots

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, what I would need to merge this is understand how this contributes to the game.

"Fix the missing wall problem for the blood tile" - what is the missing wall problem?

**Comment by YashKumarVerma** [comment]
@AirWolfXD  Updates ?

**Comment by STEdirisuriya** [comment]
@AirWolfXD Please squash your commits and tell us what you fixed!

**Comment by AirWolfXD** [comment]
Before I did this, a wall in a tile I made was missing so I added a new wall and changed the other wall to make the doorway go in the correct place.

**Comment by AirWolfXD** [comment]
capture

**Comment by YashKumarVerma** [comment]
Thanks for your contribution

**Pull request merged**
