### PR TITLE
Added a new task, Life-and-Death

### PR DESCRIPTION
**Pull request by Beta-King**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### Links

[http://rawgit.com/USERNAME/labyrinth/BRANCH-NAME/index.html]

### CODE REVIEW

**Comment by Beta-King** [comment]
Please review and merge :D @niccokunzmann

**Comment by saarthakchats** [comment]
Please elaborate

**Comment by Beta-King** [comment]
Ohk so for example, create a gui - gollem - when you enter the tile containing that gollem your life should decrease and if you fall into a number of such tiles (Traps) you will eventually die. After each time an element(gollem) damages you then a message should pop-up with a short line for example - the gollem smashed you, etc. After and when you die a message should pop-up saying for-example - You died! Try again...  Something like this :D

**Comment by Beta-King** [comment]
@saarthakchats ohk ??

**Comment by arjunpandey2003** [comment]
Hey, I think instead you could add it as an issue and work on it as a new feature. If this task is there it will only have one instance since after it is added no point of the task.

**Comment by Beta-King** [comment]
No but more elements can be added na...

**Comment by saarthakchats** [comment]
I agree with @arjunpandey2003

**Comment by Beta-King** [comment]
New and creative elements can be added to several different tiles as the task requires only one tile to contain the element so more than one instance can be created :D @arjunpandey2003

**Comment by Beta-King** [comment]
Ohk, i can do that in that way then :D

**Pull request closed without merging**
