### PR TITLE
Fixes #208 : Entire Codebase formatted

### LINKED ISSUE #208: Format Entire Codebase
### Expected results
A well-formatted codebase

### Actual results
Files are ill-structured and difficult to comprehend.

### Steps to reproduce the issue
- format the entire codebase
  - [x] gui.js
  - [x] inventory.js
  - [ ] level.js- claimed 
  - [x] levels.js
  - [x] player.js
  - [x] tiles.js

## Would you like to work on this
All Should. Time to time needed.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
This pull request is related to issue #208  

The problem I want to solve is: as mentioned is #208 

My steps to solve it:
Changes: 
[x] Formatted entire codebase
[x] Separate commits to track edits in file 

Screenshots/Links:[Deploy/Preview Links: ](http://rawgit.com/yashkumarverma/labyrinth/master/index.html)

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Okay. This is very important to have a clean code base. Now, you know which files have a conflict. 
Could you create a new pull request for the three files which worked?
Then, I think, it would be good not only for you, to create 1-3 new pull requests with the other problematic files.
If you do it tomorrow between 9GMT and 12 GMT, I might be there to merge fast so we reduce conflict for you and others.

What do you think?

**Comment by niccokunzmann** [comment]
You can use git `cherry-pick 912d30f ` to get the level.js commit into a new branch.

**Comment by YashKumarVerma** [comment]
@niccokunzmann How about closing this now and throwing a new pr right now ?

**Comment by niccokunzmann** [comment]
Sure. I saw some and merged. Closing this.

**Comment by YashKumarVerma** [comment]
sure @niccokunzmann .adding more.

**Pull request closed without merging**
