### PR TITLE
Add new features and improve UI

### PR DESCRIPTION
**Pull request by kubami9**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
  http://rawgit.com/kubami9/labyrinth/master/index.html

  This is PR #551 made the right way
  Solves point 1st, 2nd, 4th and partly 3rd points of #519 

### The problem I want to solve or the facility I want to improve is/are
 - add restart game button
 - add change character (in game) button
 - new character pick system (prototype, still needs improvements)
 - like/dislike game section/box

### My steps to solve it
 - add restart game button
 - add change character (in game) button
 - new character pick system (prototype, still needs improvements)
 - like/dislike game section/box

Not everything here is fully perfect but as talked in #551 we're going to improve parts which need improvements in further PRs, we wouldn't like to make too big PR which is hard to maintain (also, see #551 )

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
The character picker is showing greatly. But we not added a way to pick them to play yet. because GCI going to end. So we will surely improve it from next PR, @niccokunzmann Kindly merge this before conflicts

**Comment by niccokunzmann** [comment]
@kubami9 @STEdirisuriya Sorry, I just merged with conflicts but it should be resolvable.

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
@kubami9  @STEdirisuriya I reverted it because of license issues. Please re-create the pull request without the greensocks file.

**Comment by kubami9** [comment]
@niccokunzmann do we need to create new issue for it? And do you know which is the greensocks file? Supun is already sleeping and he was the main contributor of this new character system, if possible I'd like to fix it now so it can be merged as fast as possible 😅

**Comment by niccokunzmann** [comment]
See the chat https://gitter.im/fossasia/labyrinth?at=5a5e6605ae53c15903f6b626

**Pull request merged**
