### PR TITLE
Added hover property for languages in how to play page

### LINKED ISSUE #638: No hover property for language options in How to Play
### Expected results
On hovering over the language colour should change.
link: http://rawgit.com/fossasia/labyrinth/master/howtoplay.html
### Actual results
No such change.
### Implementation/Solution Ideas
Add hover property.
### Would you like to work on this
Yes.

### PR DESCRIPTION
**Pull request by harsh-jindal**
### Changes done in this Pull Request
Added hover property for languages in how to play page. 
 link:- http://rawgit.com/harsh-jindal/labyrinth/branch1/howtoplay.html
  Fixes #638 
### The problem I want to solve or the facility I want to improve is/are
No hover for languages.
### My steps to solve it
Added hover property.
File Changed: howtoplay.html

### CODE REVIEW

**Comment by DNS-404** [comment]
The change is good. Nicely done but why did you change the indentation a lot? I’m currently working on correcting indentation of all the files and then I’ll create a documentation for it. I indented this file yesterday. You changed it all. Please don’t leave any spaces before html, head and body tags. All the other sub tags(in head and body) will have 2 spaces before them. That’s what I’m following. Also, I’m not completely sure about this myself but shouldn’t all the css be at the same place? It’s a general practice to keep html and css separate. We should follow it. You should add the css to custom.css

**Comment by harsh-jindal** [comment]
@DNS-404 I'm sorry I didn't focus on indentation. And regrading css part of it there is no specific place defined for css. And I think the custom.css is for css changes made in index.html.
I guess we don't want to mix them. And even the contributors.html has it own css, so why not this?
I guess it would be better if the css for these pages is included within them.
If u want I can make the changes again with proper indentation?

**Comment by harsh-jindal** [comment]
@DNS-404 I have now made the changes in stylesheet.css
And also indented the file as I had worked on this issue before your commit was merged.

**Comment by niccokunzmann** [comment]
@DNS-404 Would you like to review?

**Comment by DNS-404** [comment]
@niccokunzmann Yeah sure!

**Comment by DNS-404** [comment]
@harsh-jindal Okay. It’s still different. I told you no spaces before head and body. I know that it’s difficult to change it again and again. So how about you fetch the latest commits and create the change in css again?

**Pull request closed without merging**
