### PR TITLE
Adding New Character : Sheep

### PR DESCRIPTION
**Pull request by YashKumarVerma**
## A sheep which leads !

My steps :
- [x] Added new character to game. (inspired from https://www.freepik.com/, edited to need)
- [x] Added to character dropdown 

Screenshots/Links:
(Deploy/Preview Links:) [http://rawgit.com/yashkumarverma/labyrinth/inventory/index.html]

image

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you rsolve the conflicts?

**Comment by YashKumarVerma** [comment]
@abishekvashok Done 😄

**Comment by YashKumarVerma** [comment]
@niccokunzmann

**Comment by niccokunzmann** [comment]
It is soo sweet O-O. Thanks for your added character. I think, you know about licensing and made sure all is legal. We can also talk about that if you have doubts.

**Comment by YashKumarVerma** [comment]
Everything was legal 😄

**Pull request merged**
