### PR TITLE
Add Background Music

### PR DESCRIPTION
**Pull request by akshit15013**
Description : Add your own background music
Preview link : https://pr-839-fossasia-labyrinth.surge.sh/
Issue No. : #840

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
@akshit15013 Could you please give a preview link?

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, COULD YOU PLEASE MERGE IT?

**Comment by STEdirisuriya** [comment]
@akshit15013 and convert your `.mp3` file into `.ogg`. @niccokunzmann recommended it to me.

**Comment by akshit15013** [comment]
Ok

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, COULD YOU PLEASE MERGE IT?

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, CAN YOU PLEASE MERGE IT?

**Pull request merged**
