### PR TITLE
Healing : Fixes entire game, back to working state

### LINKED ISSUE #370: the game is not working
### Expected results
Make game working

### Actual results
not working

## Would you like to work on this
I am working

### LINKED ISSUE #373: A lot of bugs appearing
### Expected results

Usual few bug issues.

### Actual results

Lately, we opened a lot of bug issues.

### Suggested steps

Please identify the bugs and help us with code / documentation to identify changes with a bug.

Ideas:
- syntax errors: travis check which is red when there is a syntax error
- walking through tiles: document walls/tiles and add some check if the picture is in the walls/doors directory

### PR DESCRIPTION
**Pull request by YashKumarVerma**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.
***not done purposely***

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  **Here you can add your preview link--**
- [Preview Link](http://rawgit.com/yashkumarverma/labyrinth/healing/index.html)
# Fixes #370 ✨ 
# Fixes #373  🎇 

# Game back to working state

@niccokunzmann , sorry to ping but urgent

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
@niccokunzmann , this gets the game to working state. can we have it merged ?

**Comment by niccokunzmann** [comment]
@YashKumarVerma I would like to merge. Could you resolve conflicts, also I created a pull request before #382 which might have resolved that, so this is why there are conflicts now.

**Comment by YashKumarVerma** [comment]
Sure

**Comment by YashKumarVerma** [comment]
Since you've done the changes what o wanted to do, I think that's enough. The need of this pr is satisfied, so shall we close this?

**Pull request closed without merging**
