### PR TITLE
Fixed #116: Added Text

### LINKED ISSUE #116: Text
caro.svg is a blank tile and doesn't have any text 
Working on it

### PR DESCRIPTION
**Pull request by samyakbvs**
I have added text to the caro.svg file

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Link to preview?

**Comment by niccokunzmann** [comment]
In order to keeps the game changes transparent - understandable by most contributors, we need some help:
- a preview link, so we see this is useful
- a problem and solution description, both divided, often in the issue
- an issue which does not describe changes but your motivation to make the changes and how this improves someone's life

Could you help us understand your motivation?

**Comment by samyakbvs** [comment]
I am making this change as the tile looks to blank rn

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/jainsamyakjain-labyrinth/

**Comment by abishekvashok** [comment]
@samyakbvs some tiles are not rendering can you check?

**Comment by samyakbvs** [comment]
Thanks

**Comment by niccokunzmann** [comment]
Thanks! @abishekvashok I think this is because it is based on an old version.

**Comment by samyakbvs** [comment]
Still @abishekvashok I will see what you are talking about in my next PR

**Pull request merged**
