### PR TITLE
add solution ideas to sync about the way to go

### PR DESCRIPTION
**Pull request by niccokunzmann**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  **Here you can add your preview link--**
- [Preview Link](http://rawgit.com/USERNAME/labyrinth/BRANCH-NAME/index.html)
- Fixes`#<Issue no.>`
, 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,

In the currently open issues, I rarely see the proposed plan of action
If someome sees the issue, they might not be able to solve it.

### My steps to solve it,

Add solution ideas.

### Screenshots,
[If any]

### CODE REVIEW

**Comment by abishekvashok** [comment]
Update the template @niccokunzmann and this is ready to go

**Comment by niccokunzmann** [comment]
@abishekvashok Which template would you like me to update?

**Comment by abishekvashok** [comment]
Your PR body @niccokunzmann 
You have'nt ticked this.
>  Read and understood see CONTRIBUTING.md
Included a Preview link and screenshot showning after and before the changes.
Included a description of change below.
Squashed the commits.

**Comment by abishekvashok** [comment]
Maybe add something to it.

**Comment by niccokunzmann** [comment]
Okay, I ticked it.

**Comment by niccokunzmann** [comment]
Preview is in the /files from here.

**Comment by abishekvashok** [comment]
You did'nt gave me time to get you an approve :(

**Pull request merged**
