### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #127: Changes to PR template
### Expected results
Detailed info added
### Steps to reproduce the issue
Update the template
## Would you like to work on this
Yes I am working on this

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes #127 

The Problem I want to solve is: The PR needed some minor changes, along with addition of info

Changes:Updated PR template. Added necessary info and gave some examples.

Screenshots./links: If you want to check out the new template please visit my fork at: https://github.com/arjunpandey2003/labyrinth

screen shot 2018-01-04 at 12 46 07 pm

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Would you like to follow your own template for this pull request?

**Comment by arjunpandey2003** [comment]
@niccokunzmann done.

**Comment by arjunpandey2003** [comment]
@niccokunzmann can you take a look

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by arjunpandey2003** [comment]
welcome!

**Pull request merged**
