### PR TITLE
Added my self drawn tile

### PR DESCRIPTION
**Pull request by samyakbvs**
I added my self-drawn tile to expand the labyrinth maze with something unique

### CODE REVIEW

**Comment by samyakbvs** [comment]
Pls merge this one without a preview link

**Comment by samyakbvs** [comment]
Pls merge this one without a preview link

self_made
Screenshot the tile

**Comment by samyakbvs** [comment]
@niccokunzmann

**Comment by niccokunzmann** [comment]
@YashKumarVerma Thanks for the review!

**Comment by niccokunzmann** [comment]
@samyakbvs Thanks for another tile.

**Pull request merged**
