### PR TITLE
Added a new Character: AngryBot

### PR DESCRIPTION
**Pull request by Beta-King**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### Links

http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by Beta-King** [comment]
Please review and merge :D

**Comment by Beta-King** [comment]
thanks for the review :D

**Comment by Beta-King** [comment]
Thanks :D

**Comment by Beta-King** [comment]
@niccokunzmann please review and merge :D

**Comment by arjunpandey2003** [comment]
@Beta-King there is a slight white background, please remove it else looks good

**Comment by Beta-King** [comment]
could you tell me how to change the background to transparent :D @0x48piraj

**Comment by 0x48piraj** [comment]
Ask Google :+1:

**Comment by Beta-King** [comment]
Yeah i think i got it; making changes in a bit :D

**Comment by Beta-King** [comment]
@0x48piraj , made the chages - review now :D

**Comment by 0x48piraj** [comment]
Also, Squash the commits.

**Comment by Beta-King** [comment]
Thats what im doing :D

**Comment by Beta-King** [comment]
wait a min...

**Pull request closed without merging**
