### PR TITLE
Created a tile and added it

### PR DESCRIPTION
**Pull request by samyakbvs**
I created a tile and added it, I did it to expand the app further

Test link - http://rawgit.com/samyakbvs/labyrinth/master/index.html

### CODE REVIEW

**Comment by samyakbvs** [comment]
@niccokunzmann

**Comment by samyakbvs** [comment]
Now is it fine @duttaditya18 and @niccokunzmann

**Comment by niccokunzmann** [comment]
Thanks.

**Comment by niccokunzmann** [comment]
@samyakbvs @duttaditya18 If you have ideas about small improvements, you can add them to #103 or open new issues. If you have an idea about what would be a good way to name tiles and to order them, this is suitable for documentation. The documentation is binding in a way that we must not break it and should follow it.

**Comment by samyakbvs** [comment]
Okay @niccokunzmann

**Pull request merged**
