### PR TITLE
Added new character: Geekomoji

### PR DESCRIPTION
**Pull request by sagarreddy2003**
Added a new character to labyrinth as per google code-in task.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@sagarreddy2003 Thanks for your pull request. I would like to merge the character. In the mean time other people added characters. Could you resolve the merge conflict?

**Comment by sagarreddy2003** [comment]
I think I'm good now.

**Comment by sagarreddy2003** [comment]
I'm new to Github. I resolved the conflict, I don't know why it still says that there is a conflict...

**Comment by niccokunzmann** [comment]
Yes, thanks!

**Comment by niccokunzmann** [comment]
@sagarreddy2003 Please submit the GCI task. https://codein.withgoogle.com/dashboard/task-instances/6199782437552128/

**Pull request merged**
