### PR TITLE
[WIP] remove the code duplication in the controls

### PR DESCRIPTION
**Pull request by niccokunzmann**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
There is code duplication and there does not need to be duplicated code.

### My steps to solve it,
use the existing functions

### Links

http://rawgit.com/fossasia/labyrinth/remove-handler-duplication/index.html

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Does anyone know why I get a syntax error here?

**Comment by abishekvashok** [comment]
weird

**Comment by niccokunzmann** [comment]
okay, this was in the labyrinth, see #227

**Comment by niccokunzmann** [comment]
@abishekvashok now, it works. No syntax error, please someone review.

**Comment by abishekvashok** [comment]
Late. But it looks good.

**Pull request merged**
