### PR TITLE
Added Desert Theme and a New Character

### LINKED ISSUE #186: Add a New Theme
### Expected results
Add a New Theme to the Game
### Actual results
There are only a few themes
### Steps to reproduce the issue
Work on a new theme
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #186

The problem I want to solve is: Add a Theme

My steps to solve it:
Changes: Added Files related to the Desert Theme.

This will work as soon as #161 got fixed.
Ping @niccokunzmann 
  
Extra Features

- Added a New Character
- Added a New Level

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@naveentherocker Thanks, I would like to merge it as soon as possible. 

A hint: if you create pull requests one for each different change, it gets merged faster: I could not already merge the desert theme. 
Thanks for integrating the desert theme in this way, too. I am sure we can use it once #161 is solved.

**Comment by naveentherocker** [comment]
Sure. No problem. From the next time i'll send different PRs for each change @niccokunzmann

**Comment by xeon-zolt** [comment]
@naveentherocker please check merge conflicts

**Comment by naveentherocker** [comment]
@xeon-zolt Fixed the Conflicts

**Comment by niccokunzmann** [comment]
Thanks for the new theme!

**Comment by naveentherocker** [comment]
My Pleasure @niccokunzmann

**Pull request merged**
