### PR TITLE
Create snape

### PR DESCRIPTION
**Pull request by ann31**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [ ] Included a description of change below.
- [ ] Tried to [squash the commits][squash].
- [ ] Added Screenshot to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-{PULL-REQUEST-NUMBER}-fossasia-labyrinth.surge.sh

- Fixes #<Add issue number here>

### Screenshots, Location of Changes

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by abishekvashok** [comment]
Do you wish to add it to the game? See the readme for the instructions :)

**Comment by ann31** [comment]
yes , i do wish to add it to the game. i have read the readme.

**Comment by abishekvashok** [comment]
Can you make the change done in #931 appear here and close it?

**Comment by ann31** [comment]
screen shot 2018-11-26 at 2 27 12 pm

changes made:
      updated gui.js to include new character "snape"

**Pull request closed without merging**
