### PR TITLE
Added a Functionality (Cake and Spoon :D)

### PR DESCRIPTION
**Pull request by Beta-King**
http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by Beta-King** [comment]
Please review and merge the PR :D

**Comment by saarthakchats** [comment]
I don't think this makes much sense, there should be a restriction to passing. For example -- the Boat was mandatory to cross the river tile. The cake won't actually stop you from crossing if you think about it.

**Comment by Beta-King** [comment]
Its not about that; how will you eat it without a spoon -- thats the point -- Its just a fun addition !! @saarthakchats

**Comment by saarthakchats** [comment]
You dont have to eat. You can just walk by

**Comment by Beta-King** [comment]
Could you elaborate please @saarthakchats

**Comment by samyakbvs** [comment]
I think what he basically means is that there is no use of this function as the player can just pass by the tile and the cake won't stop him from doing it @Beta-King

**Comment by saarthakchats** [comment]
Exactly

**Comment by saarthakchats** [comment]
I told you, just like you cant cross the river without the boat

**Comment by Beta-King** [comment]
the cake tile will block the player from entering if the player does not have a spoon to eat the cake @saarthakchats

**Comment by Beta-King** [comment]
@saarthakchats -- that would be the case in real life, however for the purpose of a game i've added this so that the player needs the spoon to eat the file or else the tile is unreachable to the player :D

**Comment by Beta-King** [comment]
Thanks @samyakbvs :D

**Comment by Beta-King** [comment]
Its a game; it is impractical -- think about it -- even in the boat thingy -- labyrinths are underground caves in real life so how can rivers and boats be there -- anyways Thank you for the approval @saarthakchats :D appreciate it !!

**Comment by Beta-King** [comment]
Thanks @Valley-valley @sayak119 :D

**Comment by niccokunzmann** [comment]
Thanks! I also read your discussion and I smile!

**Pull request merged**
