### PR TITLE
Add Dog Character

### PR DESCRIPTION
**Pull request by Mattythewie**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Tried to [squash the commits][squash].
- [x] Added Screenshot to Indidate Location of Change in Game
- [x] Added issue #875

### Changes done in this Pull Request

- View my work at https://pr-877-fossasia-labyrinth.surge.sh

- Fixes #<Add issue number here>

### The problem I want to solve or the facility I want to improve is/are
adding 1 more character.

### My steps to solve it

added dog.svg to labyrinth/characters.
modified labyrinth/js/gui.js file to be able to prompt dog character to be picked.

### Screenshots, Location of Changes

screen shot 2018-11-22 at 12 12 07 pm
screen shot 2018-11-22 at 12 13 12 pm

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by Mattythewie** [comment]
Apologies, still new to this and not clear how the preview link works.

**Comment by Mattythewie** [comment]
@abishekvashok @YashKumarVerma Was it not deleted in my second commit?

**Comment by abishekvashok** [comment]
Can't see your commit, it's not deleted yet and there are conflicts.

**Comment by Mattythewie** [comment]
Ok noted @abishekvashok

**Pull request closed without merging**
