### PR TITLE
Added music to Forbidden Tile

### PR DESCRIPTION
**Pull request by amryarios**
Courtesy of bensound.com

http://rawgit.com/amryarios/labyrinth/master/index.html

Addition #245

### CODE REVIEW

**Comment by amryarios** [comment]
Ping @niccokunzmann :)

**Comment by amryarios** [comment]
Add license? Is not site bensound.com already included license ? @abishekvashok

**Comment by niccokunzmann** [comment]
Yep, license is in the folder. All fine, thanks!

**Comment by niccokunzmann** [comment]
I am not sure if it is playing though.

**Pull request merged**
