### PR TITLE
[Review Needed] Added Tamil Translation 

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-1038-fossasia-labyrinth.surge.sh

- Fixes #<Add issue number here>

### Screenshots,Path to Tile

screenshot 19
screenshot 20
screenshot 21

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by NishithP2004** [comment]
Shall I remove bundle exec img_checker ,the reason why the travis build is failing.

**Comment by abishekvashok** [comment]
In my opinion We don't need translations

**Comment by abishekvashok** [comment]
However it fits, let's do it

**Comment by NishithP2004** [comment]
`Please merge` @abishekvashok @saarthakchats

**Comment by NishithP2004** [comment]
@abishekvashok @saarthakchats @YashKumarVerma Please merge

**Comment by NishithP2004** [comment]
> __ database

@renosbest what do you mean by that??

**Pull request merged**
