### PR TITLE
Fixes #241 :Improved code quality

### LINKED ISSUE #241: Need to improve Code Quality of index.html
Needs better indented code

Working on it

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #241 
Improved code quality, better indentation and removed blank spaces

### CODE REVIEW

**Comment by saarthakchats** [comment]
@harshit98 
Who is allowed to merge PRs in this repo

**Comment by saarthakchats** [comment]
@niccokunzmann Pls merge

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
Usually, we would have travis run and tell us what the code should look like. Code quality improvements are good in this way: We stick to one style and we do not have commits like these which potentially create merge conflicts. I will look again, if we can activate travis.

**Comment by YashKumarVerma** [comment]
@niccokunzmann will this be considered for the improve code quality task ?

**Comment by niccokunzmann** [comment]
Yes.

**Comment by niccokunzmann** [comment]
I will consider it. But I also read the description of the task on GCI when it is submitted and see if there is a problem with the way it is submitted. So I check there. Generally, I separate GCI and the development as GCI is competitive and development is cooperative. Both are kind of opposites. To answer why I am writing this: Just writing yes I do not know if I really understood but I am sure we will figure this out^^

**Comment by YashKumarVerma** [comment]
Got it 😄

**Pull request merged**
