### PR TITLE
Added a character

### LINKED ISSUE #923: add a new character
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser Name and version:
* Link to your project:
* Machine Configuration: Ram, Graphics Memory

### PR DESCRIPTION
**Pull request by RahulMetre03**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at  https://pr-939-fossasia-labyrinth.surge.sh

 https://rahulmetre03.github.io/gci18/

- Fixes #923 

### The problem I want to solve or the facility I want to improve is/are

I have added a Mario character

### My steps to solve it

I have added Mario.png in characters folder and made code changes in gui.js in js folder.
### Screenshots, Location of Changes, Path to Tile

image

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by RahulMetre03** [comment]
Oh sorry I'll just make @YashKumarVerma

**Comment by RahulMetre03** [comment]
@YashKumarVerma Is it alright now?

**Comment by YashKumarVerma** [comment]
Fixes is followed by an issue number. you've posted the pull request number

**Comment by RahulMetre03** [comment]
But it's a GCI Task  @YashKumarVerma

**Comment by RahulMetre03** [comment]
OKay @saarthakchats

**Pull request closed without merging**
