### PR TITLE
added new play link

### PR DESCRIPTION
**Pull request by YashKumarVerma**
# :fireworks:  GAME IN LIVE :fireworks: 

### *[labyrinth-live.surge.sh](http://labyrinth-live.surge.sh/)*

---

Check the last time the site was updated from this repo at 
*[http://labyrinth-live.surge.sh/status.html](http://labyrinth-live.surge.sh/status.html)*

***checked every minute for update***

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I merged it because it is better than what we had before.

#761 is still not tackled.

**Comment by niccokunzmann** [comment]
Would you recommend surge for live links for new contributors?

**Comment by YashKumarVerma** [comment]
I tried it. But it gave errors.

**Comment by YashKumarVerma** [comment]
Please check my fork of labyrinth. And see the travis.yml file. And also the deploy.sh file.

I tried to automate everything, but surge broke during travis run

**Pull request merged**
