### PR TITLE
Fixes#154. Update footer.css

### PR DESCRIPTION
**Pull request by arjunpandey2003**
This pull request is related to issue #154 

The problem I want to solve is: There was a really dull background

My steps to solve it:
Changes:Footer.css Added a gradient

Screenshots/Links: http://rawgit.com/arjunpandey2003/labyrinth/master/index.html
Check out the background
screen shot 2018-01-05 at 12 55 13 pm

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
thanks @YashKumarVerma

**Comment by niccokunzmann** [comment]
@arjunpandey2003 Thanks! I merged the master branch. You can have a look if I did that right. I will merge now so we can have your changes integrated. If I made a mistake, please open a new pull request or an issue.

**Comment by arjunpandey2003** [comment]
yes i think it is done

**Comment by arjunpandey2003** [comment]
thanks @niccokunzmann

**Pull request merged**
