### PR TITLE
Add folder with README and license for CC0 License tiles Fixes #424

### LINKED ISSUE #424: Create pixbay folder and license
### Expected results

There are tiles which use content which is under CC0.
I expect to see
- a folder for these tiles
- a LICENSE in the folder which is from pixbay
- a README which states when to add tiles there.

### Actual results

Nothing like this but
- merged #419 
- pull request #420

### PR DESCRIPTION
**Pull request by kubami9**
Add folder with README and license for CC0 License tiles

### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- Fixes`#424>`

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
Add folder for tiles licensed under CC0 License with `license.md` and `README.md`. Fixes #424.

### My steps to solve it,
 - Create proper folder structure for tiles.
 - Create `license.md` file
 - Create `README.md` file

*Please tell me if there is anything else I should include in any of this files so this PR can completely solve an issue.*

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, could you put this into tiles/cc0 ? Like this, we have a new folder.

**Comment by kubami9** [comment]
Done and squashed.

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
#424

**Pull request merged**
