### PR TITLE
Added new wall

### PR DESCRIPTION
**Pull request by Shizerq**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].

### Changes done in this Pull Request

- View my work at https://pr-{787}-fossasia-labyrinth.surge.sh

- Fixes none. That's task from Google Code-In

### The problem I want to solve or the facility I want to improve is/are

I've done task from Google Code-In (create new wall)

### Screenshots
screenshot 2018-11-02 at 15 43 54

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
You can refer this
- https://github.com/fossasia/labyrinth#how-to-add-new-tiles
- https://github.com/fossasia/labyrinth/pull/763

**Comment by Shizerq** [comment]
I've included the tile to the game

**Comment by Shizerq** [comment]
Added tiles to the game.

**Comment by YashKumarVerma** [comment]
> I've included the tile to the game

can you post the screenshot of the tile in game ? So that we can find it easily ?

**Comment by Shizerq** [comment]
How can i preview my tile?

**Comment by niccokunzmann** [comment]
Hi, thanks. I merged this so we can use it.
If you like to add it to the game in the future, that would be great!

**Pull request merged**
