### PR TITLE
Audio added

### PR DESCRIPTION
**Pull request by arihantbansal**
Audio added

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [ ] Added Screenshot to Indidate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-883-fossasia-labyrinth.surge.sh

- Fixes #<Add issue number here> 884

### My steps to solve it

Added my own composed background music for the game.

### Screenshots, Location of Changes

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by arihantbansal** [comment]
Please merge.

**Comment by YashKumarVerma** [comment]
I think you should open a issue regarding this as mentioned in contributing.md

**Comment by arihantbansal** [comment]
Added

**Comment by YashKumarVerma** [comment]
> Added

Not Complete. https://github.com/fossasia/labyrinth/tree/master/.github/ISSUE_TEMPLATE has the templates. Use the music one

**Comment by arihantbansal** [comment]
Issue description changed. Please merge.

**Pull request merged**
