### PR TITLE
Change death note graphic

### PR DESCRIPTION
**Pull request by Sartech-B**
change death note graphic for characters!

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by YashKumarVerma** [comment]
isn't death note a copyright of madhouse studios ? @niccokunzmann 
https://en.wikipedia.org/wiki/Death_Note

**Comment by niccokunzmann** [comment]
Yes, could be. A black rectangle with text is not a copyright problem. I think it counts as fan work and art. Nothing was copied as I see it. What do you think?

**Comment by YashKumarVerma** [comment]
Yup. O agree to it. Was just concerned because it could have been a violation. Now we're clear about it 😃

**Pull request merged**
