### PR TITLE
add a song change dialog

### LINKED ISSUE #1035: Add a switch song version
### How to use the Feature
Change the song by a drop down preferably
### How the Feature Improves the Game
Easy and Quick Track Change
### Implementation/Solution Ideas
A dropdown for the same would be efficient
### Would you like to work on this
yes

### PR DESCRIPTION
**Pull request by pythongiant**
fix styles:

fix styles

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-1036-fossasia-labyrinth.surge.sh
https://pythongiant.github.io/labyrinth/

- Fixes #1035 

### Screenshots,Path to Tile

image

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by saarthakchats** [comment]
also, show the names of the creators everywhere

**Comment by pythongiant** [comment]
@saarthakchats check it out now. Did some changes you requested

**Comment by pythongiant** [comment]
@saarthakchats I can make the pointer but what do you mean by a hover

**Comment by pythongiant** [comment]
@YashKumarVerma

**Comment by saarthakchats** [comment]
Hover effect

**Comment by saarthakchats** [comment]
The colour should become lighter or something like that on hover

**Comment by saarthakchats** [comment]
> did the pointer

It's not correct; either play the song on clicking anywhere on the box, or only change the pointer ont the play button.
It feels like tge entire block is a button to play but it is not.

**Comment by pythongiant** [comment]
got it. making changes

**Comment by pythongiant** [comment]
@saarthakchats check it out now. did all changes you asked.

**Comment by saarthakchats** [comment]
> It's not correct; either play the song on clicking anywhere on the box, or only change the pointer ont the play button.
> It feels like the entire block is a button to play but it is not.

This is not fixed

**Comment by pythongiant** [comment]
Ummm i think there is a misunderstanding here @saarthakcgats. Would you please tell me which block are we actually talking about here? If its the block where we click the song by clicking the play button the song is playing.
Thanks

**Comment by saarthakchats** [comment]
> > did the pointer
> 
> It's not correct; either play the song on clicking anywhere on the box, or only change the pointer on the play button.
> It feels like the entire block is a button to play but it is not.

The blocks in your dropdown list

**Comment by pythongiant** [comment]
Oops forgot to push changes to my gh branch. Lemme do that and should work

**Comment by pythongiant** [comment]
@saarthakchats everything should be alright now

**Comment by saarthakchats** [comment]
> > did the pointer
> 
> It's not correct; either play the song on clicking anywhere on the box, or only change the pointer ont the play button.
> It feels like the entire block is a button to play but it is not.

This is still not fixed

**Comment by pythongiant** [comment]
the pointer only changes when hovering on the play button.
please clear your browser cache and see again @saarthakchats. you can even browse through the code. please look into it

**Comment by YashKumarVerma** [comment]
Can the play button color be white ?

**Comment by pythongiant** [comment]
Hmm @YashKumarVerma I am pretty sure that's due to some style defined previously. Still lemme see what I can do about this

**Comment by pythongiant** [comment]
@YashKumarVerma @saarthakchats I deleted the unnecessary hover changes. check it out now. 
CC: @abishekvashok

**Comment by abishekvashok** [comment]
Thanks, great work!

**Pull request merged**
