### PR TITLE
[WIP] Restoring two tiles as they do not work properly :D

### PR DESCRIPTION
**Pull request by Beta-King**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  **Here you can add your preview link--**
- [Preview Link] http://rawgit.com/Beta-King/labyrinth/master/index.html
- Fixes`#<Issue no.>`
, 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### CODE REVIEW

**Comment by Beta-King** [comment]
@samyakbvs would you like to work on restoring these tiles together as they are your creations ??

**Comment by samyakbvs** [comment]
You already fixed them, haven't you?

**Comment by samyakbvs** [comment]
Hey @Beta-King Don't delete the tiles

**Comment by Beta-King** [comment]
No, the tiles are not aligned the way they should have been

**Comment by Beta-King** [comment]
We need to re-design them

**Comment by samyakbvs** [comment]
Don't you think fixing them is a better option as they also have nice functionality in them

**Comment by samyakbvs** [comment]
@Beta-King Only the size is the problem nothing else

**Comment by Beta-King** [comment]
ohk so lets make the size appropriate then :D

**Comment by samyakbvs** [comment]
So pls fix it instead of delting the tiles

**Comment by Beta-King** [comment]
ohk, You wanna work on this too or should i continue without ??

**Comment by samyakbvs** [comment]
If you csn do it alone I am fine bcs this is a minor issue and I don't think it requires collab

**Comment by Beta-King** [comment]
Yeah ohk ill do it myself, i just wanted you to be considered in the process as they are your tiles, but yups i can fix them :D

**Comment by samyakbvs** [comment]
Sure go ahead brother!

**Comment by samyakbvs** [comment]
They are still out of order

**Comment by samyakbvs** [comment]
And can you tell me where is the second tile

**Comment by samyakbvs** [comment]
@Beta-King

**Comment by Beta-King** [comment]
Fixing it, please wait :D

**Comment by samyakbvs** [comment]
Sure!

**Comment by samyakbvs** [comment]
If you want help I am here

**Comment by Beta-King** [comment]
@samyakbvs --> is it solved now ??

**Comment by samyakbvs** [comment]
Preview link?

**Comment by Beta-King** [comment]
Its above in the inital comment

**Comment by arjunpandey2003** [comment]
@Beta-King you have still deleted the files pls restore the tiles

**Comment by samyakbvs** [comment]
That one is not updated

**Comment by Beta-King** [comment]
which files are you talking about ??

**Comment by Beta-King** [comment]
How do i update it then ??

**Comment by samyakbvs** [comment]
Try deploying it again

**Comment by Beta-King** [comment]
Deploying as in ??

**Comment by niccokunzmann** [comment]
@samyakbvs Thanks for the review.
@Beta-King Thanks for taking the time to improve the game.

**Pull request merged**
