### PR TITLE
Add documentation about how to add files to the audio folder

### PR DESCRIPTION
**Pull request by niccokunzmann**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), #284 #245 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
There is no clear documentation about how to legally embed sound into the game.

### My steps to solve it,
- add the documentation
- give credit to the existing 2 files with known origin

### CODE REVIEW

**Comment by tmncollins** [comment]
...

**Comment by tmncollins** [comment]
Add

**Comment by niccokunzmann** [comment]
Okay, thanks for the review @tmncollins :)

**Comment by saarthakchats** [comment]
@niccokunzmann 
I think we should add to the documentation... "How to license you code"

**Pull request merged**
