### PR TITLE
[Please comment] Add GCI Tasks

### PR DESCRIPTION
**Pull request by niccokunzmann**
The problem I want to solve is
- that we need the GCI tasks somewhere for next year.
- that we can give a good overview over the tasks
- that we can develop and improve the tasks here and move them to GCI later.

My solution for the problem is 
- add all the tasks and the new tasks in this directory

If you like to improve the tasks so you like them better, you can create a pull request to the gci-tasks branch or comment below.

### CODE REVIEW

**Comment by naveentherocker** [comment]
I have few task ideas

- Add a New Feature to Labyrinth
- Solve an Advanced Issue
- Create an object. Ex-River, Trees, Road and Vehicles

**Comment by niccokunzmann** [comment]
@naveentherocker Cool, I would like to incorporate them. Would you like to create a pull request to the GCI branch?
I have these questions:
1. What is a feature?
2. Should be tag issues as advanced then, this sounds good to me :)
3. Where will this object be used? (Just submitting a picture does not make it part of the labyrinth.)

**Comment by naveentherocker** [comment]
1.  Something like Implementing Points System, Leaderboard, Multiplayer options and etc.
2.  Yes. If you just put a task named `Fix an Issue`, then Participants will look for small bugs. If `advanced` is there, they must work on some big issues which are already tagged as `advanced` or they can do a bug hunt and fix them
3. It's better if there are many objected to the game rather than only Rooms.

**Comment by niccokunzmann** [comment]
1. I understand. I will write something.
2. Yes, should be https://github.com/fossasia/labyrinth/pull/67/commits/073132179df4162f086400abb8b8cbcfef1b9854
3. This is what I mean with "landscape". Uh, I see there is no task like this..... hm...

**Comment by naveentherocker** [comment]
Fine :)

**Comment by YashKumarVerma** [comment]
---

# Labyrinth: Build/Inprove the UI of the game

The [FOSSASIA Labyrinth](https://github.com/fossasia/labyrinth/) allows you to contribute parts to a huge labyrinth.
To extent the labyrinth, please add a new level.

Requirements:
- Add the basic UI elements to the game / Improve if they already exist.
- Develop / Enhance the on-screen controls.

Expected Outcome:
- A nice modern UI for the game

Hints:
- If someone wants to work with you, let them do that. You can use techniques like [pair programming](https://www.youtube.com/watch?v=vgkahOzFH2Q) or collaborate together on branches of your forks. You can attribute a pull-request also to other people who helped you out or submit a pull-request where you and an other person contributed together.
- You can join our [chat on gitter](https://gitter.im/fossasia/labyrinth) if you get stuck to get help or just hang out and have a nice time with others.

---

Categories:
- [X] Code
- [X] User Interface
- [ ] Documentation / Training
- [x] Quality Assurance
- [ ] Outreach / Research

**Comment by niccokunzmann** [comment]
Would you like to create a pull request to the tasks directory and we discuss this? I would like to add that task as it perfectly fits what @duttaditya18 in #87 and we can use that many times.

There are three things which I would like to make more objective: "improve" "nice" and "modern".
We could say, that we want to copy designs from other pages and this should as fancy as there, so we can have a reference link and a pull request link and a picture in the pull request submitted.

I want the mentors and students to be clear what to expect and not a discussion about what is nice, is not nice/was better before.

What do you think?

**Comment by YashKumarVerma** [comment]
Sure. Would be throwing in a pr in few hours. Preparing for an exam that i have to appear tomorrow 😂

**Comment by duttaditya18** [comment]
@YashKumarVerma Subject?

**Comment by duttaditya18** [comment]
@niccokunzmann When can I expect to see the proposed GCI tasks?

**Comment by YashKumarVerma** [comment]
@duttaditya18 Same question 😆

**Pull request merged**
