### PR TITLE
Adds animated fairy's wheel tile

### PR DESCRIPTION
**Pull request by abishekvashok**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- Adds animated fairy's wheel tile to the labyrinth. Modified neccessary
scripts to make it accessible.
- [Preview Link](http://rawgit.com/abishekvashok/labyrinth/king/index.html)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Note game is not working on my fork as it is not working in the upstream repo (this repo)

**Comment by abishekvashok** [comment]
@xeon-zolt can you review?

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by abishekvashok** [comment]
Welcome

**Pull request merged**
