### PR TITLE
Create a new character: Shadowman

### PR DESCRIPTION
**Pull request by abishekvashok**
This pull request is related to issue: Not related. It's related to a GCi task.

Screenshots/Links:[Deploy/Preview Links: http://rawgit.com/abishekvashok/labyrinth/jack/index.html]

screenshot_20180106_111436

Summary:
Adds a new character shadowman to the game. Adds svg file and
implementation in gui.js

### CODE REVIEW

**Comment by duttaditya18** [comment]
@abishekvashok He is not visible in some tiles. Do you think you can do something about that?

**Comment by duttaditya18** [comment]
@abishekvashok Damn those annoying Merge Conflicts! 😄

**Comment by abishekvashok** [comment]
Fixed em

**Comment by abishekvashok** [comment]
@niccokunzmann I don't know whether you are buys, you sent a rather strong msg in the channel, but as of the instructions pls review this.

**Comment by niccokunzmann** [comment]
I will trust @duttaditya18 with the review. I am here once a day at least. But if I have more time, I will take more time :) Just so you know what you can expect.

**Comment by abishekvashok** [comment]
Sure

**Pull request merged**
