### PR TITLE
Added a new Hand-Drawn Tile :D

### PR DESCRIPTION
**Pull request by Beta-King**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### Links

http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by Beta-King** [comment]
Please review and merge :D

**Comment by samyakbvs** [comment]
Pls send screenshot of the image

**Comment by Beta-King** [comment]
screen shot 2018-01-10 at 12 00 51 am

**Comment by Beta-King** [comment]
Screenshot given @samyakbvs :D

**Comment by Beta-King** [comment]
Thanks :D @samyakbvs

**Comment by saarthakchats** [comment]
@Beta-King Please dont use emoji notations in PR message, rest looks good

**Comment by Beta-King** [comment]
@saarthakchats --> could you approve then ??

**Comment by Beta-King** [comment]
image --> working well in the game :D

**Comment by saarthakchats** [comment]
Looking great!

**Comment by niccokunzmann** [comment]
Thanks for the review, thanks for the tile!

**Comment by Beta-King** [comment]
Thank you guys @saarthakchats @niccokunzmann

**Pull request merged**
