### PR TITLE
Added music to my tile: yellow :D

### PR DESCRIPTION
**Pull request by Beta-King**
http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by Beta-King** [comment]
Thanks :D

**Comment by Beta-King** [comment]
#444 --> contributes to this issue :D

**Comment by Beta-King** [comment]
@sayak119 did as you commanded :D could you approve now ??

**Comment by sayak119** [comment]
@Beta-King just add Fixes #issue_number in your PR

**Comment by niccokunzmann** [comment]
Thanks for the pull request and review!

**Pull request merged**
