### PR TITLE
Added a hand drawn tile-Salt

### LINKED ISSUE #975: Add a new hand drawn tile
### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Draw a floor.
- [x] Draw a wall.
- [x] Draw another wall or mirror the existing one.
- [x] Scan or photograph the pictures if they are hand-drawn.
- [x] Add the pictures to the [tiles folder].
- [x] Edit the [tiles.js] file to include the new tile.
- [x] Place the tile in the labyrinth.
- [x] Check that you can not walk through walls in the code and the labyrinth.

### Closing Criteria

- [x] The tile is added to the labyrinth and reachable. Please provide the directions.
- [x] The tile is properly rendered.

### PR DESCRIPTION
**Pull request by NishithP2004**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [ ] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-1016-fossasia-labyrinth.surge.sh

- Fixes #975 

### Screenshots,Path to Tile

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by NishithP2004** [comment]
screenshot_2018-12-09-20-39-26-457_com android chrome
@abishekvashok @YashKumarVerma Please help to solve this error.

**Comment by Ryan10145** [comment]
@NishithP2004 You added the definition for the salt tile to the collection of tiles for dark in tiles.js, however, you referenced it as door.salt in levels.js. Move the definition for the salt tile to line 1473 of levels.js, inside of the door object.

**Comment by NishithP2004** [comment]
@Ryan10145

**Comment by NishithP2004** [comment]
@Ryan10145 I have added it to the dark realm but the Travis build is still failing.

**Comment by Ryan10145** [comment]
@NishithP2004 The Travis build is failing for a different reason, it's because some of the images unrelated to your change do not satisfy the proper image dimensions. I would suggest that you provide screenshots/a path to your tile as well as a preview link so that we can review your change. The images will likely be fixed in another PR.

**Comment by NishithP2004** [comment]
@Ryan10145 I am not able to find the tile in the dark realm . Could you locate it?

**Comment by NishithP2004** [comment]
@abishekvashok I meant that I am unable to find my tile in the dark realm in the preview link.

**Comment by NishithP2004** [comment]
@abishekvashok Are you able to locate it?

**Pull request closed without merging**
