### PR TITLE
Added new song: Cute to the background :D

### PR DESCRIPTION
**Pull request by Beta-King**
http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by Beta-King** [comment]
screen shot 2018-01-14 at 10 09 36 am --> it works :D

**Comment by Beta-King** [comment]
@samyakbvs , @abishekvashok , @rupav , @harshit98 --> please review this :D

**Comment by Beta-King** [comment]
thanks @abishekvashok

**Comment by Beta-King** [comment]
@niccokunzmann --> please review and merge this PR :D

**Comment by niccokunzmann** [comment]
@Beta-King There is a documentation about how to add music. Please follow one of the styles, not both half. This is to keep the project understandable. Also CC-BY-ND means we need to give credit to people. Please give credit in the license file. 
You may choose to add the music file to the bensound folder.

**Comment by Beta-King** [comment]
alright :D making changes ASAP :D

**Comment by niccokunzmann** [comment]
Looks good!

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by Beta-King** [comment]
Thank you :D

**Pull request merged**
