### PR TITLE
Revert "Resized all images to fix Travis checks"

### PR DESCRIPTION
**Pull request by niccokunzmann**
Reverts fossasia/labyrinth#1021
Reverting this as a possible fix for #1026 and to deploy it and have a look.

https://pr-1045-fossasia-labyrinth.surge.sh

### CODE REVIEW

**Comment by niccokunzmann** [comment]
This fixes the issue #1026. However, it does not fix the build.

**Comment by niccokunzmann** [comment]
@saarthakchats @abishekvashok before I try to do it by myself, I would value your input as you have worked on the checks as I can see and have experience. What do you think? Do you have suggestions?

**Comment by saarthakchats** [comment]
The image tracker will naturally fail as this PR reverts the resizing.. the other issue was with rake
That I dont know who put in the checks.. you can look around and try to fix @niccokunzmann

**Comment by abishekvashok** [comment]
Let's merge it here, and for individual tiles maybe we should really take a look and see how they should be scaled. Let's make the game playable now

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
