### PR TITLE
Added a new character

### LINKED ISSUE #923: add a new character
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser Name and version:
* Link to your project:
* Machine Configuration: Ram, Graphics Memory

### LINKED ISSUE #955: Added a character
Description
Added a new CHARACTER 'Mario'

Implementation Plan
 Step 1:Added a image with proper dimensions
 Step 2:Updated the gui.js file
 Step 3:Added a new character

Closing Criteria
 Criterion 1:The character is available for a player to begin with the game
 Criterion 2:All the details are filled properly

### PR DESCRIPTION
**Pull request by RahulMetre03**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-947-fossasia-labyrinth.surge.sh

 https://rahulmetre03.github.io/gci18/.
- Fixes #955

### The problem I want to solve or the facility I want to improve is/are

I have added a Mario character

### My steps to solve it

I have added Mario.png in characters folder and made code changes in gui.js in js folder

### Screenshots, Location of Changes, Path to Tile

![image]
image

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
1. pr description incomplete
2. no issue linked with pr. usually I don't ask to link issues from first time contributes but since you are not, you've to provide one.

**Comment by RahulMetre03** [comment]
It's done @YashKumarVerma

**Comment by RahulMetre03** [comment]
Is it okay? @YashKumarVerma

**Comment by abishekvashok** [comment]
Wrong issue number, consider adding a new issue.

**Comment by RahulMetre03** [comment]
Its all done! @YashKumarVerma  @abishekvashok

**Comment by RahulMetre03** [comment]
Is everything okay now?

**Comment by abishekvashok** [comment]
I don't know why but I can't see the image.

**Comment by RahulMetre03** [comment]
Which one? @abishekvashok

**Comment by RahulMetre03** [comment]
Now? @abishekvashok

**Comment by abishekvashok** [comment]
You need to design your character, was it designed by you? If so, please make it in the correct ratio

**Pull request closed without merging**
