### PR TITLE
Remove Zeichnung Lasse.svg image file from the project

### LINKED ISSUE #782: Remove Zeichnung Lasse.svg
This file is not needed I hope. It should be removed.

### PR DESCRIPTION
**Pull request by parammittal16**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].

### Changes done in this Pull Request

- Fixes #782 

### My steps to solve it

Remove Zeichnung Lasse.svg image file from the root directory

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Is characters/Zeichnung Lasse.svg really not needed? Can you check that?

**Comment by parammittal16** [comment]
@YashKumarVerma  Zeichnung Lasse.svg in the characters directory has been restored. Plz review.

**Comment by YashKumarVerma** [comment]
As it is a minor change, which doesn't change the functioning of țhe game, I'm merging it @niccokunzmann 

Good work @parammittal16  :+1:

**Comment by parammittal16** [comment]
@YashKumarVerma Thanks

**Pull request merged**
