### PR TITLE
[Resolved #793 and #796] Some bugs are solved

### LINKED ISSUE #793: Left navigation slider only opens and doesnt get close
### Present behaviour
Clicking on the nav burger opens the navigation slider but clicking on it after that doesnt closes it but scrolls the page to the top

### Expected behaviour
Clicking on the nav burger should toggle the nav slider - close it if it is open and open it if it is closed.

**My screen size:** 1920 x 1080
**Browser:** Chrome 69
And I'd like to help in fixing this

### LINKED ISSUE #796: Weird hover over "select your language" in the navbar
hoverbug
## Present behaviour
Hover on the parent of "select your language" element turns the parent's bg light green and then moving to the text turns it bg light green and triggers the dropdown
## Expected behaviour
Hovering on the parent itself should do all that

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash]. 

### Changes done in this Pull Request

Me(@STEdirisuriya) and Ammar(@ammarbinfaisal) resolved the major bugs were in labyrinth interface. 
I resolved #796 and Ammar resolved #793.
We thought to left 3 commits because this is a collaborate PR. I think it's fine. 
So I think it's not need to squash more than that.

Thank you!

Edit by @YashKumarVerma 
https://pr-802-fossasia-labyrinth.surge.sh

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
Sorry I couldn't squash more than this, there a lot of ahead commits in main repo. I think this will be fine.

**Comment by ammarbinfaisal** [comment]
@saarthakchats [see this](https://ammarbinfaisal.github.io/labyrinth)

**Comment by YashKumarVerma** [comment]
Codacy is failing. Please check.

**Comment by STEdirisuriya** [comment]
> Codacy is failing. Please check.
failtures in js/sidebar.js were come from earlier PRs. Other failtures I removed.

**Comment by ammarbinfaisal** [comment]
@YashKumarVerma checked the js errors.  
I've declared navburger and a property of window object and that is why codacy is saying that it isnt defined. I had to do that because if I keep it at the top of the file and declare it using var then it would be probably be null(dont remember what it was). I am declaring it in window.onload method (making it a property of window object) so that it remains accessible in the event handling functions.

And the other issue is that I am using function closeSideBar before it is defined. I dont see what is wrong with this as closeSideBar function is not an arrow function(it has been defined using function().. syntax) and thus it is hoisted.

**Comment by YashKumarVerma** [comment]
As I see, the language selected is working fine (note that the icons are missing)

**Comment by STEdirisuriya** [comment]
@YashKumarVerma Which Icons?

**Comment by STEdirisuriya** [comment]
> As I see, the language selected is working fine (note that the icons are missing)

I don't know who removed the icons!

**Comment by STEdirisuriya** [comment]
>As I see, the language section is working fine (note that the icons are missing)

It's now working properly.  Have a look please

**Comment by ammarbinfaisal** [comment]
@saarthakchats I explained why it is failing above. I cant find a workaround

**Comment by niccokunzmann** [comment]
I cannot see that codacy is a requirement in the documentation. Thanks for your contributions! I am merging this, had a look over the code and the game.

**Pull request merged**
