### PR TITLE
Added a new character

### PR DESCRIPTION
**Pull request by samyakbvs**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [x] Included description of change below.
- [x] Tried to [squash the commits][squash].
- [ ] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

I have added a new character (Pacman) to the game.

- View my work at https://pr-1060-fossasia-labyrinth.surge.sh/

- Fixes #<Add issue number here>

### Screenshots,Path to Tile

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
in future commits, a more informative commit name would be very appreciated.

**Comment by samyakbvs** [comment]
Can someone merge this PR?

**Comment by samyakbvs** [comment]
Sure @YashKumarVerma

**Comment by YashKumarVerma** [comment]
# :tada: Good Work

**Pull request merged**
