### PR TITLE
Added Archer character

### PR DESCRIPTION
**Pull request by mikolajhojda**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
  http://rawgit.com/USERNAME/labyrinth/master/index.html

- Fixes #<Add issue number here>

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@mikolajhojda There is a checklist at the top of this pull request with four items. Would you like to do something of it? We use that to keep track of changes and on-board people to the process.
I invite you to follow it or change it: https://github.com/fossasia/labyrinth/blob/master/.github/PULL_REQUEST_TEMPLATE.md
The process should be uniformly and binding to ensure we can work with the contributions in a consistent way.

I reviewed your change and can merge it. Would you like to have it merged now or check some items before?

**Comment by mikolajhojda** [comment]
@niccokunzmann I checked.

**Comment by niccokunzmann** [comment]
> Included a preview link and screenshot showing after and before the changes.

I see that this is hard as we do not know how to show the game as a website at the moment.

>  Included a description of change below.

I do not see where you did this. I would expect something like "add character XY". Can you show me where this is? By the way: you can edit the description at the top.

**Comment by niccokunzmann** [comment]
> Squashed the commits.

I see two commits. I do not think you must do that as it is hard for beginners, see #757. If you like, you can try it and we help you :)
What do you think?

**Comment by mikolajhojda** [comment]
@niccokunzmann 
Before: before
After: 
aftersrc
after2src
site: https://mikolajhojda.github.io/labyrinth/

I apologize for the problems. I'm a beginner.

**Comment by niccokunzmann** [comment]
I played it with the archer, great. Thanks!

**Comment by niccokunzmann** [comment]
This repository is for you and beginners. So, it is just that way that we talk a lot here :)

**Comment by mikolajhojda** [comment]
@niccokunzmann Thanks for the help.

**Comment by abishekvashok** [comment]
Link to task: https://codein.withgoogle.com/dashboard/task-instances/6254012400664576/

**Pull request merged**
