### PR TITLE
Fixes #94 : Add .editorconfig for linting purposes

### LINKED ISSUE #94: Add .editorconfig for linting purposes
Linting Purpose for Javascript

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #94

### CODE REVIEW

**Comment by naveentherocker** [comment]
@niccokunzmann Please Review

**Comment by niccokunzmann** [comment]
@naveentherocker Thanks for the pull request!
@abishekvashok Thanks for reviewing.

**Comment by naveentherocker** [comment]
You are Welcome @niccokunzmann and Thanks @abishekvashok

**Comment by abishekvashok** [comment]
Welcome

**Pull request merged**
