### PR TITLE
Added animated tile: square

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [ ] Screenshot of Change
### Changes done in this Pull Request

- View my work at https://pr-834-fossasia-labyrinth.surge.sh
- I added an animated tile, square.

Thank you!

### CODE REVIEW

**Comment by abishekvashok** [comment]
The animation does work, but it overflows out the tile, and overlaps the walls.

**Comment by STEdirisuriya** [comment]
@YashKumarVerma I resolved the conflicts. 
@abishekvashok I think it's fixed now. 
image

**Comment by abishekvashok** [comment]
See it flowing out of the tile.

**Comment by STEdirisuriya** [comment]
@YashKumarVerma I have resolved conflicts. I moved the animation to center.
tile

**Comment by STEdirisuriya** [comment]
@YashKumarVerma thank you!

**Pull request merged**
