### PR TITLE
Added an animated tile and changed the tile.js

### PR DESCRIPTION
**Pull request by ecomparer**
This pull request is related to issue # 

Changes:
I added an animated tile called fossasia_express which features a fossasia bullet train.
I changed the tile.js to add my  tile info.

Screenshots/Links:[Deploy/Preview Links: http://rawgit.com/USERNAME/labyrinth/master/index.html]

### CODE REVIEW

**Comment by abishekvashok** [comment]
This looks good :) , however these are the things that you can do:

- Resize the tile to correct dimensions
- Call the object levels.js
- Squash the commits

**Comment by ecomparer** [comment]
i preferred it to be smaller than the dimensions so that it would stay within the walls.
Some animations i have noticed go out of those walls.
I could rename it to levels.js tho.

**Comment by abishekvashok** [comment]
> i preferred it to be smaller than the dimensions so that it would stay within the walls.

If that is so pls add it in the exactly same dimensions as it is there in cairo.svg and other tiles.

**Comment by ecomparer** [comment]
there is no tile such as cairo.svg

**Comment by abishekvashok** [comment]
oh sorry pls see: tiles/room/floor/cairo.svg
@ecomparer

**Comment by niccokunzmann** [comment]
@ecomparer Thanks for you pull request. If someone could add the tile in the future, that would be great to play with.
@abishekvashok Thanks for taking the time to suggest ideas. It also works if they are scaled down by a factor. Since the tile does not display right now, please open a minor issue or create a pull request. You can also revert this and argue that this improves the game.

**Pull request merged**
