### PR TITLE
Fixed files characters: swammy.svg and daredevil.svg

### LINKED ISSUE #404: There is a problem with the daredevil.svg image
### Expected results

- Create images according to their size ie 55 x 60
- Eliminates the white image that surrounds the image

### Actual results
- The image is 357 x 483
- It looks white around the image

image

### Steps to reproduce the issue

I will change the image to the correct size of 55 x 60, and also remove the white part of the image using Inkscape.

## Would you like to work on this
Yes of course

### PR DESCRIPTION
**Pull request by amryarios**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  **Here you can add your preview link--**
- [Preview Link](http://rawgit.com/amryarios/labyrinth/master/index.html)
- Fixes #404 #206 
, 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
- In the image daredevil.svg size 357 x 483 and also there is white around the picture
- In the swammy.svg image there is white around the picture

### My steps to solve it,
- Eliminate the white on the image and also resize the image to 55 x 60 on the daredevil.svg image
- Eliminate white on image in swammy.svg

### CODE REVIEW

**Comment by amryarios** [comment]
@niccokunzmann  :+1:

**Comment by amryarios** [comment]
Thanks :+1:  @duttaditya18

**Comment by niccokunzmann** [comment]
Thanks for the description. I like to get in touch with motivations!

**Comment by amryarios** [comment]
@niccokunzmann I also like to work with you, you are very friendly :) :+1:

**Comment by amryarios** [comment]
Please accept my task https://codein.withgoogle.com/dashboard/task-instances/4831665702567936/  :+1:

**Pull request merged**
