### PR TITLE
Pull Request #700: Responsive menubar to stop the menu from overlapping onto Logo.

### PR DESCRIPTION
**Pull request by himanshuc3**
### Changes done in this Pull Request

- css/custom.css - Added media queries to the bottom of file.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi @himanshuc3. Thanks for your pull request.
I would like to understand what this is for? Do you solve an issue? In which way does this improve the game for you?

**Comment by himanshuc3** [comment]
Hi @niccokunzmann . That was fast. Anyway,

**Before Commit (On master branch)** 
screen shot 2018-02-05 at 4 01 44 pm
screen shot 2018-02-05 at 4 01 56 pm

**Improved behaviour after commit** 
screen shot 2018-02-05 at 4 02 38 pm

**Comment by niccokunzmann** [comment]
Preview Link:  http://rawgit.com/himanshuc3/labyrinth/Issue%23700/index.html

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
I could reproduce it and indeed: I see the menu much better when the size of the screen is smaller.

**Pull request merged**
