### PR TITLE
Added docs to play game, get's game back to working state. Fixes #34, Fixes #42

### LINKED ISSUE #34: Document how to play the game
You need the arrow keys, up down right left to move in the labyrinth.
But no-one knows!
Please add it somewhere

- When the game starts (most important)
- In the README

### LINKED ISSUE #42: When I open labyrinth there are no things appears.
I am using UBUNTU and firefox browser.

see222
see2222
broke

I am trying to fix.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
- Added docs to play game #34 
- Fixed the broken game #42

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
@niccokunzmann 

this pr gets the game back to working state. So,it's a bit urgent. sorry to bug you.

**Comment by niccokunzmann** [comment]
Thanks a lot!

**Comment by YashKumarVerma** [comment]
It's ***our game*** ❤️

**Comment by niccokunzmann** [comment]
Would you like to link this next to **Play Now** ?

**Comment by YashKumarVerma** [comment]
sure !

**Comment by YashKumarVerma** [comment]
throwing in a pr.

**Pull request merged**
