### PR TITLE
Added level Space

### PR DESCRIPTION
**Pull request by sahilsaha7773**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-922-fossasia-labyrinth.surge.sh

- Fixes #<Add issue number here>

### The problem I want to solve or the facility I want to improve is/are

Added a level Space.

### Screenshots, Location of Changes

ll

ll2

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by sarnava1** [comment]
Also please squash the commits

**Comment by sahilsaha7773** [comment]
jj

Added some space tiles though they are not clearly visible in the screenshot due to the surge window.

**Comment by sahilsaha7773** [comment]
@YashKumarVerma

**Comment by sahilsaha7773** [comment]
Please merge

**Comment by sahilsaha7773** [comment]
Thanks for merging!!

**Pull request merged**
