### PR TITLE
Add a wall

### PR DESCRIPTION
**Pull request by akshit15013**
Description : Add a wall right
Issue No. : #813 
screenshot 121

### CODE REVIEW

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, CAN YOU MERGE IT?

**Comment by Ryan10145** [comment]
@akshit15013 Follow this template: https://github.com/fossasia/labyrinth/blob/master/.github/PULL_REQUEST_TEMPLATE.md . When you first make the pull request, the text should appear automatically and you just have to fill in the details.

Also, you should add in a preview link or at least a screenshot of your work so that we can better review it. Look at #763 or #787 as examples.

**Comment by akshit15013** [comment]
@Ryan10145 Is it Ok now?

**Comment by akshit15013** [comment]
@YashKumarVerma How can I add a tile to a game?

**Comment by akshit15013** [comment]
@YashKumarVerma Is it Ok now?

**Comment by akshit15013** [comment]
I HAVE A MODIFIED CODE, CAN YOU MERGE IT?

**Comment by YashKumarVerma** [comment]
Can you post the screenshot of the tile in game? So that it can be found easily by anyone whose reviewing?

**Comment by akshit15013** [comment]
@YashKumarVerma I do not know how to do that?

**Comment by akshit15013** [comment]
@YashKumarVerma Could you please merge it?

**Pull request closed without merging**
