### PR TITLE
Added my Yellow Tile :D 

### PR DESCRIPTION
**Pull request by Beta-King**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### Links

http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by niccokunzmann** [comment]
: D

**Comment by niccokunzmann** [comment]
I just played it: I will create an issue to improve this one.

**Comment by niccokunzmann** [comment]
Thanks for the tile, now we have one more!

**Comment by niccokunzmann** [comment]
@Beta-King Your code is perfect! I could use this one right away.

**Comment by Beta-King** [comment]
no i think there is a problem with the image (.svg files) !!

**Comment by Beta-King** [comment]
Thank you :D

**Pull request merged**
