### PR TITLE
removing content from readme

### PR DESCRIPTION
**Pull request by YashKumarVerma**
removing docs from readme

## Reason
The same data is added to the `/documentation` directory, and is no longer needed in readme.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Please also add why you do this.

**Comment by duttaditya18** [comment]
@YashKumarVerma Do not plug your name wherever you contribute. You have written your name in every single block in the Documentation. 

It is collective effort.

**Comment by YashKumarVerma** [comment]
apologies @duttaditya18 , the reason for that is that i am using a python script and (trying to automate) things. So it adds my name to every entry (because it picks it up from a template). The concept is to put the name of the person/contributor who wrote that section of the game.

We can remove it if needed. I'll put up a demo link there now. Sorry for the inconvenience.

**Comment by duttaditya18** [comment]
@YashKumarVerma Don't be sorry! 😄 I just think this is not right.

How many times have you seen an Open Source software with names of the contributors in the main screen? I think it should be removed.

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
