### PR TITLE
Adds graphics level

### PR DESCRIPTION
**Pull request by abishekvashok**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

### Changes done in this Pull Request

- Adds graphics level which is for the intense new generation graphics
people with graphical mania!
  
  http://rawgit.com/abishekvashok/labyrinth/master/index.html

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks! Are you sure the tests run? Currently, travis takes a long time. Could you run the scripts in the scripts folder and post the output?

**Comment by abishekvashok** [comment]
@niccokunzmann travis ci is facing a bit of problems I guess. It's on a que. Here is the outputs
screenshot_20180114_214830
screenshot_20180114_214851

**Comment by abishekvashok** [comment]
To restart travis ci. OR is it ready @niccokunzmann

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
Would you like to add it to be chosen and accessible? You can have a look at the goal tile.
We will need some documentation for other people, too. If you like, you can add it and I review or I do it.

**Comment by abishekvashok** [comment]
> Would you like to add it to be chosen and accessible?

Sure but I am out of sync with the code of labyrinth, that is why I am staying a bit away...

**Comment by abishekvashok** [comment]
@niccokunzmann I see but it just loads the forest level. I should not change that right?

**Pull request merged**
