### PR TITLE
Added tiles

### PR DESCRIPTION
**Pull request by ddx-510**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request
Added svg file floor, door and wall
changed tile.js
undated levels.js

- If your change will be reflected on the website, please provide a **Test-Link**
  **Here you can add your preview link--**
- [Preview Link](http://rawgit.com/ddx-510/labyrinth/master/index.html)
- Fixes`#<Issue no.>`
, 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Could you check and resolve merge conflicts? I would like to merge.

**Comment by ddx-510** [comment]
How to check whether it is okay now

**Comment by duttaditya18** [comment]
@ddx-510 Resolve merge conflicts.

**Comment by ddx-510** [comment]
ah... could tell me the methods to resolve the conflicts?

**Comment by duttaditya18** [comment]
@ddx-510 Click on the green button which says resolve merge conflicts.

And then follow this : 
https://help.github.com/articles/resolving-a-merge-conflict-on-github/

I know it is a bit complicated but please try. Resolving merge conflicts is a really important skill.

Good luck!

**Comment by ddx-510** [comment]
ok.  btw, is it not nice to use proprietary in open source project ..next time will avoid that thx

**Comment by duttaditya18** [comment]
@ddx-510 Nice! You fixed the conflicts! Now wait for merging.

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
