### PR TITLE
Create create a new scratch project

### PR DESCRIPTION
**Pull request by knahsahs1004**
Expected Outcomes:
1.the game will be played
2.and can also be shared
3.children can learn programming language

### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### Links

[http://rawgit.com/USERNAME/labyrinth/BRANCH-NAME/index.html]

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@knahsahs1004 Thanks for your idea. Please see 
https://github.com/fossasia/labyrinth#implementation

It might be that scratch is not part of this.
What do you think?

**Comment by niccokunzmann** [comment]
I hear you like scratch and would like to make have a task for that. Meybe the promo video task fits  where you create a promo scratch project about the game?

**Comment by niccokunzmann** [comment]
Please also see the added documentation: https://github.com/fossasia/labyrinth/tree/master/tasks

**Comment by YashKumarVerma** [comment]
Please no 😐

**Comment by duttaditya18** [comment]
Don't think this is needed.

**Comment by niccokunzmann** [comment]
If there is three days no progress, I will close it. This is tomorrow. We can always open it again and discuss.

**Pull request closed without merging**
