### PR TITLE
Fixes #142 : Deleted Contributor links which were not serving right purpose

### LINKED ISSUE #142: Centralize all contributors
### Expected results
All the contributors should be at one place.

### Actual results
All the contributors added their name and linked it, It breaks the game and practically sways away the attention of the player.

### Screenshots

image

---

image

## Would you like to work on this

Yes!

### Approach : 

I know, they have contributed and there work should be appraised, but it should be at one place.
I'll design the `README.md` and will add all the contributors with their work.
*It will be helpful if the contributors help in this by adding their credits* :+1: :100: 

> It's not a GCI Task, just for the game!

---
What you think @niccokunzmann ?

### PR DESCRIPTION
**Pull request by 0x48piraj**
> It's not a good practice to put names and modify the end product.
You should sign the codebase, via using comments *(if you have done an incredible job and you're proud at it.)*

@niccokunzmann I think it is now looking even better !
image

**_Test-Link : http://rawgit.com/0x48piraj/labyrinth/delete/index.html_**

> It's not a GCI Task!

### CODE REVIEW

**Comment by 0x48piraj** [comment]
@niccokunzmann I think this can be a very good pair programming issue! What do you think ?

**Comment by YashKumarVerma** [comment]
I'm in if you need a partner 😋

**Comment by 0x48piraj** [comment]
Sure! We'll make add all contributors on `README.md` and will make a separate contributors page. 
What do you think @YashKumarVerma ?

**Comment by niccokunzmann** [comment]
@duttaditya18 Thanks for the review.. an all others for reviewing. This speeds up m work because I don't have to review.

**Pull request merged**
