### PR TITLE
[IN PROGRESS] Added a Larva Character

### PR DESCRIPTION
**Pull request by Jeewal**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://jeewal.github.io/labyrinth/
There is no issue for this. it was for a GCI task.

### The problem I want to solve or the facility I want to improve is/are
I want to add a larva character 

### My steps to solve it
I added larva.svg to the characters folder 
I also added larva to the gui.js file

### Screenshots, Location of Changes, Path to Tile

larva
larva1

### CODE REVIEW

**Comment by jakubpawlina** [comment]
It is generally correct but why your character's image has dimensions 930 x 480 px? [Here](https://github.com/fossasia/labyrinth#how-to-add-a-new-character) you can find, that it should be about 55 x 60 px (wxh).

**Comment by Jeewal** [comment]
image
i hope the problem is resolved.

**Comment by YashKumarVerma** [comment]
Labyrinth has a set of Issue Templates to standardize the development.

Consider using them. That can be found at 
https://github.com/fossasia/labyrinth/tree/master/.github/ISSUE_TEMPLATE

Thanks for your contribution to the community.

**Comment by Jeewal** [comment]
Thank You for the Templates ! :)

**Pull request closed without merging**
