### PR TITLE
Tiles

### PR DESCRIPTION
**Pull request by maddymmt**
I am not sure about the size of tiles, if they are acceptable. Despite of given sizes by fossasia.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
We will see that once it is integrated into the game.
If you like to get inspiration, you cansee the documentation or search past pull requests with tiles.

**Comment by niccokunzmann** [comment]
What would you like to do?

**Comment by rannmann70** [comment]
Cool

**Comment by niccokunzmann** [comment]
Okay, since you waited so long, I will merge and create an issue for you with a step-by-step guide.

**Pull request merged**
