### PR TITLE
[Fixed #815] Added timer, and suitable translations

### LINKED ISSUE #815: Adding a timer.
When we need it to be a competition, we need a points system and a timer. 
I am going to add a timer. 

I am working on this!

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].

### Changes done in this Pull Request
- Added the timer #815 which starts when the player moves
- Added suitable translations strings from English, Sinhala, Hindi. (I failed to find the translation from Polski. I think anyone who knows Polski can add the translation in future.)
- View my work at https://pr-820-fossasia-labyrinth.surge.sh

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
Could you please help me to resolve this? 
image

I didn't see any `</p>` tag without a opening tag.

**Comment by niccokunzmann** [comment]
There could be a structure like this:

```
<X><p></X></p>
```

Can you check? Indentation can help with this.

**Comment by STEdirisuriya** [comment]
@niccokunzmann I resolved the problem. Thank you! Could you please check it again?

**Comment by YashKumarVerma** [comment]
Can we have the javascript outside index.html in some js file? 


However this is completely optional.

**Comment by STEdirisuriya** [comment]
@YashKumarVerma I will do it from another PR later. I think it's needed to improve code quality of all the files. Thank you!

**Pull request merged**
