### PR TITLE
(#1027)Added Food Party Level

### LINKED ISSUE #1027: Add a Food Party Level
### Description

Add a food-themed level to the game

### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Create a new level in [levels.js].
- [x] Create or modify a tile which allows switching to your level in [tiles.js].

### Closing Criteria

- [x] The level is added to the labyrinth and reachable. Please provide the path.
- [x] One can walk through the level.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js
[levels.js]: https://github.com/fossasia/labyrinth/blob/master/js/levels.js

### PR DESCRIPTION
**Pull request by saarthakchats**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Tried to [squash the commits][squash].
- [ ] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-1029-fossasia-labyrinth.surge.sh

- Fixes #1027 

### Screenshots,Path to Tile

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by saarthakchats** [comment]
Ping @abishekvashok @YashKumarVerma

**Comment by saarthakchats** [comment]
That's due to some other bug, probably in the .travis.yml file @Masquerade0097

**Comment by meets2tarun** [comment]
@saarthakchats 
You didn't made any edit in the .travis.yml file.

**Comment by saarthakchats** [comment]
Yeah exactly @meets2tarun 
So the travis isn't our fault

**Comment by saarthakchats** [comment]
If you check, all PRs have travis failing

**Comment by saarthakchats** [comment]
screenshot 2018-12-13 at 10 23 59 am
screenshot 2018-12-13 at 10 24 55 am

**Comment by saarthakchats** [comment]
@YashKumarVerma

**Comment by abishekvashok** [comment]
Why is the tile looking weird?

**Comment by saarthakchats** [comment]
Its a bug in the entire game

**Comment by saarthakchats** [comment]
All tiles look weird

**Comment by saarthakchats** [comment]
screenshot 2018-12-13 at 9 25 33 pm
See @abishekvashok

**Comment by abishekvashok** [comment]
The level looks cool to go, let's follow up with the tile misplacement bug in another issue :)

**Comment by saarthakchats** [comment]
@abishekvashok Okay 👍

**Comment by saarthakchats** [comment]
You merge this @abishekvashok, I would rather not merge my own PR from now

**Comment by abishekvashok** [comment]
Waiting for @YashKumarVerma

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
