### PR TITLE
Add animated tile: Mushroom

### PR DESCRIPTION
**Pull request by Ploypiti**
- [x] Read and understood [see CONTRIBUTING.md]
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
  http://rawgit.com/ploypiti/labyrinth/master/index.html

### My steps to solve it
- Add animated mushroom tile `mushroom.svg` and inventory item `PoisonedMushroom.png`

### Screenshot
image

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
How did you edit the file by hand or did you use inkscape?

**Comment by Ploypiti** [comment]
@niccokunzmann I use Adobe Illustrator : )

**Comment by niccokunzmann** [comment]
ahh ok.

**Pull request merged**
