### PR TITLE
Inventory Mechanism, Implementation : Fixes #111

### LINKED ISSUE #111: Show inventory content
### Expected results
I would like to know what the player has in the inventory #108 .

### Actual results
I can not see this on the GUI.

Implementation ideas:
- add a new item class which takes a name: a class will allow us to extend it in the future to add item abilities like combinations etc.
- There is a inventory folder with pictures to use for the items. the item loads the picture from that folder.
- when the item is added to the inventory, it is shown, when the item is removed from the inventory, it is removed from the display
- a player can not put the identical item twice into the inventory
- please use the treasure box and key tile to test this functionality

### PR DESCRIPTION
**Pull request by YashKumarVerma**
This pull request is related to issue #111  

The problem I want to solve is: *that there is a need of inventory mechanism*

My steps to solve it:
Changes: **i built the mechanism**

Screenshots/Links:
[http://rawgit.com/yashkumarverma/labyrinth/master/index.html](http://rawgit.com/yashkumarverma/labyrinth/master/index.html)

### Initially empty inventory 
image
### Keys added to inventory :card_file_box: 
image
### Treasure 💸  unleashed by the key and key redeemed. 🏆 
image
### Inventory empty again as key is already used
image

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, thanks, this looks like a solution to #111
Where did you get the key from? What license is it under?

**Comment by YashKumarVerma** [comment]
Not sure of the site but it was royalty free. I'm sure of that. It was "free to use"

**Comment by niccokunzmann** [comment]
Would it be ok if we replace the key with another key e.g. the one on the ground, so people know where they got the key from? I think there will be more keys in the future.

**Comment by YashKumarVerma** [comment]
Sure 😊.

**Comment by 0x48piraj** [comment]
I want to help you @YashKumarVerma.
I can design a key by myself!
It will be great if you'll allow me to collaborate :100:

**Comment by niccokunzmann** [comment]
@0x48piraj for example, you can create a pull request to his branch.

**Comment by YashKumarVerma** [comment]
image

**Comment by YashKumarVerma** [comment]
sorry @0x48piraj 😞 
We can work together on some other issue :clinking_glasses:

**Comment by 0x48piraj** [comment]
> See, I waited after even @niccokunzmann said to create a Pull Request.

**_Key looks cool! Cheers :wine_glass:_**

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
