### PR TITLE
Fixes #508 : Made my sword accessible

### LINKED ISSUE #508: Sword is inaccessible
Working on it!

### PR DESCRIPTION
**Pull request by saarthakchats**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
  http://rawgit.com/saarthakchats/labyrinth/master/index.html
- 
  Fixes #508 

### Screenshots,
screenshot 54

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I will wait for travis until merge.

**Comment by saarthakchats** [comment]
@niccokunzmann

**Comment by niccokunzmann** [comment]
travis takes too long. checked by myself. OK

**Comment by saarthakchats** [comment]
Ok

**Comment by saarthakchats** [comment]
Thanks

**Pull request merged**
