### PR TITLE
Resized all images to fix Travis checks

### LINKED ISSUE #989: Resize tiles and characters
## Expected Behavior
According to game standards, all tiles should be within 429.544 x 256.314 px (wxh) and all characters within 55px x 60px (wxh) .

## Current Behavior
It is startling to see that 69 images are out of dimensions.
```
The image ./tiles/rooms/floor/redFloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/wooden.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/sofa.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/orchestra.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/Monster.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/new.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/texture.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/HandDrawnTile.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/cricketGround.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/quake.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/yellowFloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/universeFloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/Random.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/goal.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/mountainsFloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/art.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/bubbleMesh.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/staircase.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/marina.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/treasureKey.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/glowL.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/guitar_case.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/mushroom.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/treasure.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/orangeFloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/river.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/graphics.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/Forest.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/quirky.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/banner-1.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/floorNewYear.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/caro.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/drawnPond.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/minecraftEntry.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/Forbidden.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/self_made.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/CreativeRoomFloor.png is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/coolsunbull.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/Desert.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/blood.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/saarthakdraw.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/live.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/banner-Chess.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/black.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/drought.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/drawnbysahil.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/minecraft.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/handarjun.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/chocolate.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/out.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/plain.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/bloodfloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/fabricate.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/staircase.png is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/batcave.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/handy.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/nightfloor.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/camel.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/hand-drawn-lines.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/handDrawnBoxes.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/boat.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/drawn.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/BeautifulMesh.svg is larger than 429.544px x 256.314px [w x h]
The image ./tiles/rooms/floor/highLow.svg is larger than 429.544px x 256.314px [w x h]
The image ./characters/witch.svg is larger than 55px x 60px [w x h]
The image ./characters/dog.svg is larger than 55px x 60px [w x h]
The image ./characters/oldman.svg is larger than 55px x 60px [w x h]
The image ./characters/cpt_america.svg is larger than 55px x 60px [w x h]
The image ./characters/pixie.svg is larger than 55px x 60px [w x h]
Image Checker: These images exceeds the specified dimensions
69 image(s) have greater dimensions then specified.
```
## Possible Solution
Resize them

## Steps to Reproduce (for bugs)
It is too much work for one individual to fix all images, so we should divide the work.
1. Each developer should pick a few images from this list and fix them
2. This process repeated by us few regular contributors can easily fix this issue quickly.
3. I would recommend every contributor to this issue to go in order.

### PR DESCRIPTION
**Pull request by saarthakchats**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Tried to [squash the commits][squash].
- [ ] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-1021-fossasia-labyrinth.surge.sh

- Fixes #989 

### My steps to solve it
- I resized 61 images and @MasterMind37 resized 8 images
- This also reduces file sizes

### Screenshots,Path to Tile

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by MasterMind37** [comment]
I confirm that I worked on this PR with @saarthakchats

**Comment by saarthakchats** [comment]
I don't think I should squash as this PR contains collaboration from 2 developers

**Comment by saarthakchats** [comment]
It worked, the image checker did not fail

**Comment by saarthakchats** [comment]
The img_checker gem did not fail.. so the images are fine now
What's failing is rake.. i don't know what that's about

**Comment by saarthakchats** [comment]
Ping @abishekvashok @YashKumarVerma

**Comment by saarthakchats** [comment]
That wasnt me 😅

**Comment by saarthakchats** [comment]
That was added by someone else, unrelated to this PR

**Comment by abishekvashok** [comment]
Please don't self merge PRs

**Comment by saarthakchats** [comment]
Sorry @abishekvashok

**Pull request merged**
