### PR TITLE
added colon in gui.js

### PR DESCRIPTION
**Pull request by RuKoBe**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  **Here you can add your preview link--**
- [Preview Link](http://rawgit.com/USERNAME/labyrinth/BRANCH-NAME/index.html)
- Fixes`#<Issue no.>`
, 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@RuKoBe Thanks. You added tree more files. Please remove them or add the .gitignore in a separate commit.

**Comment by RuKoBe** [comment]
removed .gitignore
removed OwnChar.png in project root
removed gui.js in project root

**Comment by niccokunzmann** [comment]
Cool!

**Comment by RuKoBe** [comment]
deleted the netbeans stuff, sorry, did not mention that these files came along with the commit.

**Comment by niccokunzmann** [comment]
no problem

**Pull request merged**
