### PR TITLE
Added Joker Character

### PR DESCRIPTION
**Pull request by saarthakchats**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  

- Fixes #<Add issue number here>

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@saarthakchats Thanks for your contribution!
Would you like to try to squash the commits https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git ?

**Comment by saarthakchats** [comment]
@niccokunzmann 
Squashed

**Comment by niccokunzmann** [comment]
Thanks!

Did the link for squashing help you?

**Comment by saarthakchats** [comment]
@niccokunzmann 
I already knew how to squash but I still saw the link.. it cleared some of my confusions. Thank You 😄

**Pull request merged**
