### PR TITLE
Added a new task - create-a-door.md

### LINKED ISSUE #257: Add a new task
### Expected results
New task added
### Steps to reproduce the issue
Create new file in tasks dir
## Would you like to work on this
Open for everyone.

### PR DESCRIPTION
**Pull request by saarthakchats**
Enabled a new task which is related to creating a door.
Fixes #257

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@saarthakchats This very similar to https://github.com/fossasia/labyrinth/blob/master/tasks/add-a-functionality.md Would you like to improve this task instead?

**Comment by arjunpandey2003** [comment]
@niccokunzmann as a part of functionality can we add a door?

**Comment by niccokunzmann** [comment]
Yes!

**Comment by niccokunzmann** [comment]
You hide he key somewhere and the door only opens when there is the key in the inventory e.g. So, yes, that is the idea.

**Pull request closed without merging**
