### PR TITLE
Add new theme documentation Fixes #535

### LINKED ISSUE #535: Adding new theme documentation
### Expected results
Written off how to add new them in documentation

### Actual results
There isn't anything about adding new theme in documentation

### Implementation/Solution Ideas
Add how to add new theme to documentation

### Would you like to work on this
Yes :)

### PR DESCRIPTION
**Pull request by kubami9**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [ ] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [ ] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
  http://rawgit.com/USERNAME/labyrinth/master/index.html

  Fixes #535

### The problem I want to solve or the facility I want to improve is/are
Add documentation how to add new theme

### My steps to solve it
Add documentation how to add new theme, link it to menu in `README` file

### Screenshots,
documentation_screen

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
as stated in #244 and #389 
Please convert your documentation to html, so that we can add to the documentation engine.

**Comment by kubami9** [comment]
@YashKumarVerma you mean to create it in a separate html file?

**Comment by YashKumarVerma** [comment]
yes @kubami9 ,
you can ask `niccokunzmann` sir, we can have a merger right now and then convert to html later on

**Comment by niccokunzmann** [comment]
Thanks, this is an improvement. Converting to HTML will be another improvement. Dividing content from form here.

**Comment by kubami9** [comment]
Ahh okay, thank you so much 😄

**Pull request merged**
