### PR TITLE
Added my own bg music and tile music

### PR DESCRIPTION
**Pull request by STEdirisuriya**
- [x] Read and understood [see CONTRIBUTING.md]
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to squash.

### Changes done in this Pull Request

- I added my own bg music and tile music. 
- https://stedirisuriya.github.io/labyrinth/

### CODE REVIEW

**Comment by abishekvashok** [comment]
Please choose one.

**Comment by STEdirisuriya** [comment]
@abishekvashok OK. I added one.

**Comment by niccokunzmann** [comment]
If you do not add a license, the song is GPL licensed.

**Comment by STEdirisuriya** [comment]
@niccokunzmann I added licenses. Please could you merged this now?

**Comment by STEdirisuriya** [comment]
@niccokunzmann I converted them to .ogg format thank you!

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by STEdirisuriya** [comment]
Thank you!

**Pull request merged**
