### PR TITLE
Adds character, updates GUI's JavaScript

### LINKED ISSUE #912: Telebishop
### Description
The Telebishop; a pun on 'television' and 'bishop' (the chess piece); has a head with a blue screen showing two bubbles, and a truncated cone as the base.

### Implementation Plan

- [x] Read the [documentation about adding characters].
- [x] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [x] Upload the character to the [characters folder].
- [x] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [x] The character is added to the menu to choose characters which is
  shown once the game starts.
- [x] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gui.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/

### PR DESCRIPTION
**Pull request by kuaLeYi**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link or screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].

### Changes done in this Pull Request
- Adds character file to characters
- Edits JavaScript so that tile plays music when entered
- View my work at https://kualeyi.github.io/labyrinth/
- Select 'Telebishop' at end of options on 'Choose a character' menu
- Fixes #912

### The problem I want to solve is
The FOSSASIA Labyrinth should have more characters.

### Solution
- Edits `js/gui.js` and adds `telebishop.svg` in `characters/`
- Thus, users can play as Telebishop

### Screenshots
image
After

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by kuaLeYi** [comment]
SVG, originally directly typed, fixed.

**Comment by YashKumarVerma** [comment]
Can you explain the PR title ? What GUI changes are there ?

**Comment by abishekvashok** [comment]
We can also resolve them someday ;)

**Comment by YashKumarVerma** [comment]
Thanks !

**Pull request merged**
