### PR TITLE
Increased the size of image and text in the inventory

### LINKED ISSUE #623: In the inventory size of the image and text is small
### Expected results
The image and the text can be a bit larger so that it looks better. 
### Actual results
The size of image and text is too small.
### Implementation/Solution Ideas
Increase the size of the text and the image.
### Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
### Changes done in this Pull Request
Increased the size of image and text in the inventory
 link:- http://rawgit.com/harsh-jindal/labyrinth/changes/index.html#
  Fixes #623 
### The problem I want to solve or the facility I want to improve is/are
The size of image and text in the inventory was too small.
### My steps to solve it
Increased the size of the image and text in the inventory.
Files Changed: css/materialize.min.css

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@harsh-jindal You can change this but it will be so hard to understand the changes you make there. Would it be ok if you add your changes to a new css class and write this into a css file which was created by us?

**Comment by harsh-jindal** [comment]
@niccokunzmann Okay..but these properties have been specified in css/materialize.min.css . Will it overwrite the changes I make in css/custom.css  ?

**Comment by niccokunzmann** [comment]
That depends on 
1. The order of the class names in the `class="...."` (try out)
2. If you use the same class names as materialize.min.css, the order in which the files are included (not recommended)

**Comment by harsh-jindal** [comment]
Okay..

**Comment by niccokunzmann** [comment]
@harsh-jindal Would you like me to merge it or would you like to create another pull request?

**Comment by harsh-jindal** [comment]
@niccokunzmann I'll change it in css/custom.css and see if it works there.
So don't merge it now.

**Comment by harsh-jindal** [comment]
@niccokunzmann I have now made the changes in css/custom.css

**Comment by niccokunzmann** [comment]
Okay, cool.

**Pull request merged**
