### PR TITLE
Fixes #467: Rearrange alert popup

### LINKED ISSUE #467: Alert popup overwhelmed the game
### Expected results
Continue playing without pressing _ok_ or _enter_ when the alert pops up and the alert **shouldn't** overlap the tiles; something like this:

image
### Actual results
Alerts appears too often so that it's somehow annoying to press enter everywhere you go, it ruins the overall UX as well, the game focuses on _tiles_ not popups.
### Implementation/Solution Ideas
Moving the popup aside and remove the overlapping parts. Although since if it moved aside, the popup BG would blend with the game BG, we could make the popup more noticeable, eg. change the color or move it to the top, but I think it would require the player to slides to read the whole message, and it's not healthy for user experience.

image

### Would you like to work on this
Yes, open to suggestion.

### PR DESCRIPTION
**Pull request by Ploypiti**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

### Changes done in this Pull Request

- http://rawgit.com/ploypiti/labyrinth/master/index.html
- #467

### My steps to solve it
- Rearrange the popup to the right
- Change `swal2-content` font weight
- Add _choose a character_ title

### Screenshots
image

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks so much! This is much better now.

**Comment by niccokunzmann** [comment]
I will wait for travis to confirm.

**Comment by niccokunzmann** [comment]
travis takes too long. I checked.

**Comment by Ploypiti** [comment]
@niccokunzmann Thanks for approving!

**Pull request merged**
