### PR TITLE
Added a wall

### PR DESCRIPTION
**Pull request by sahilsaha7773**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot to Indidate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://pr-889-fossasia-labyrinth.surge.sh

### The problem I want to solve or the facility I want to improve is/are

Added a wall.

**Screenshots**

ww

[squash]: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

### CODE REVIEW

**Comment by sahilsaha7773** [comment]
Will you please check my PR codewise because I am not getting my added wall at https://pr-889-fossasia-labyrinth.surge.sh/?

**Comment by sahilsaha7773** [comment]
Please tell whether it is correct codewise or not @YashKumarVerma

**Comment by sahilsaha7773** [comment]
but I am adding a wall not a theme

**Comment by YashKumarVerma** [comment]
the wall has to be added to the level too.

**Comment by sahilsaha7773** [comment]
Please merge if it is ok now

**Comment by sahilsaha7773** [comment]
Done!!

**Pull request merged**
