### PR TITLE
Added Iron Man Character and format code.

### LINKED ISSUE #857: New Character: Iron Man
### Description
Iron Man

### Implementation Plan

- [x] Read the [documentation about adding characters].
- [x] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [x] Upload the character to the [characters folder].
- [x] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [x] The character is added to the menu to choose characters which is
  shown once the game starts.
- [x] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gui.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [x] Added Screenshot to Indidate Location of Change in Game

### Changes done in this Pull Request

- View my work at https://niteshkumarniranjan.github.io/labyrinth/
- Fixes #857 

### Description

- Added a new Character "Iron Man"
- Made 4 space indentation consistent.  

### Screenshots, Location of Changes
screenshot 4

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Please change the pull request name to indicate the changes hone

**Comment by niteshkumarniranjan** [comment]
@YashKumarVerma Changed the name.

**Comment by niteshkumarniranjan** [comment]
@abishekvashok Every file in the repo has 4 space indentation so I think I have made it consistent across the repo?

**Comment by niteshkumarniranjan** [comment]
@YashKumarVerma There already some PRs being merged that didn't had any issues specified BTW. I will open one.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma There already some PRs being merged that didn't had any issues specified BTW. I will open one.

We cannot do anything of the merges that have already happened. As a maintainer, it's my duty to follow CCCC which clearly states to open issue before PR. Some PRs might have merged without auxiliary issues, but the same will not happen again.

**Comment by abishekvashok** [comment]
It's okay to be a bit of blend around it between. We should **encourage** it rather not be too strict on students.

**Comment by saarthakchats** [comment]
Also, provide all the details of the changes you made in the description

**Comment by niteshkumarniranjan** [comment]
@saarthakchats :+1:

**Comment by akshit15013** [comment]
I feel that there is an issue with the Codecy checks bacause you have changed the indentation of the file
capture
capture1

**Comment by niteshkumarniranjan** [comment]
@akshit15013 Nope.the codacy issue is because codacy want me to use ES6 syntax.

**Pull request merged**
