### PR TITLE
Added Self Composed Digital Beat to My Designed Tile

### PR DESCRIPTION
**Pull request by 0x48piraj**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Included a description of change below.

# Changes done in this Pull Request

- Created a directory consisting of my works. :+1: 
- Added a self composed digital beat :heart:
- Added Self Composed beat to my designed tile :100: 
- Created a LICENSE :+1: 

#### Screenshots : 

image

> Thanks @YashKumarVerma, I took your `LICENSE` as a template.

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Ping @niccokunzmann :heart_decoration:

**Comment by 0x48piraj** [comment]
Thanks @duttaditya18 :100:

**Comment by YashKumarVerma** [comment]
@0x48piraj anytime

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
