### PR TITLE
Added Desert Theme

### LINKED ISSUE #186: Add a New Theme
### Expected results
Add a New Theme to the Game
### Actual results
There are only a few themes
### Steps to reproduce the issue
Work on a new theme
## Would you like to work on this
Yes

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #186 

The problem I want to solve is:[Mention the bug/problem solved]

My steps to solve it:
Changes: Added Files related to the Desert Theme.

Deploy Link - http://rawgit.com/naveentherocker/labyrinth/master/index.html 
Level 3

- Please Support to modify the Tiles.

Ping @niccokunzmann

### CODE REVIEW

**Comment by duttaditya18** [comment]
@naveentherocker I see this error : 

```
ReferenceError: inventory is not defined : player.js:10:3
```

**Comment by abishekvashok** [comment]
@naveentherocker can wait for #161

**Comment by naveentherocker** [comment]
Sure. I'll work on it

**Comment by niccokunzmann** [comment]
To merge this, please

- [ ] remove indexDesert.js
- [ ] integrate your tiles into tiles.js but not inside door but inside desert
- [ ] copy your level over to the levels.js file and name it createDesertLevel()

#161 will take of loading your level

**Comment by naveentherocker** [comment]
Ok sure.

**Comment by naveentherocker** [comment]
I am closing this PR @niccokunzmann

**Pull request closed without merging**
