### PR TITLE
Added a tile `plain.svg`

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Added a tile `plain.svg`

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Ping @niccokunzmann

**Comment by YashKumarVerma** [comment]
How about adding it somewhere?

**Comment by niccokunzmann** [comment]
Okay, thanks. I do not know what this is for. Please tell me.

**Comment by 0x48piraj** [comment]
I'll add them @YashKumarVerma :+1:

**Pull request merged**
