### PR TITLE
#754 Added new character

### PR DESCRIPTION
**Pull request by AppleC4T**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
https://applec4t.github.io/AClabyrinth/

- Fixes https://github.com/fossasia/labyrinth/issues/754

### The problem I want to solve or the facility I want to improve is/are
Adding a new character

### My steps to solve it

Added new character - pixel-art, green thumbs up.

### CODE REVIEW

**Comment by AppleC4T** [comment]
@YashKumarVerma I've changed it to a fiery figure, have a look. Is that ok?

**Comment by niccokunzmann** [comment]
@YashKumarVerma

I value that you take the time to bring the labyrinth forward.

> A thumbs up as character?

Could be received as a value judgment. Please see if that is your intention.

> 14. Maintainers SHALL NOT make value judgments on correct patches.
> 18. Any Contributor who has value judgments on a patch SHOULD express these via their own patches.  
> 
> from [CCCC](https://rfc.zeromq.org/spec:42/C4/)  
> which is linked at the bottom of the README for maintainers.

**Comment by AppleC4T** [comment]
@YashKumarVerma squashed.

**Comment by niccokunzmann** [comment]
@AppleC4T Thanks!

**Comment by abishekvashok** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/5087129043468288/

**Pull request merged**
