### PR TITLE
Added a new character

### PR DESCRIPTION
**Pull request by samyakbvs**
Added a new character named Terminator

### CODE REVIEW

**Comment by samyakbvs** [comment]
terminator
An image of the new character

**Comment by samyakbvs** [comment]
http://rawgit.com/samyakbvs/labyrinth/terminator/index.html

**Comment by samyakbvs** [comment]
The size is too small I am increasing it

**Comment by arjunpandey2003** [comment]
@samyakbvs i think it needs to be your own work, it shouldn't be copied from the internet, i think

**Comment by arjunpandey2003** [comment]
plus your deploy link?

**Comment by abishekvashok** [comment]
@samyakbvs pls make your own work as provided in the task.

**Comment by naveentherocker** [comment]
@abishekvashok @samyakbvs I think that you can convert a png into svg and submit it. But i am not sure.

**Comment by abishekvashok** [comment]
@naveentherocker see the task.

**Comment by niccokunzmann** [comment]
@samyakbvs The labyrinth has two ways of looking at it:
1. GCI: the tasks says it should be your own work. You can not claim this task if this was your intention. Here, I and the mentors will check the requirements.
2. Open & Collaborative coding on github: The game is yours, do what you want. I will influence it with my experience so we can also use it in following years.
3. I will also look at legal issues: Adding other peoples work without their agreement (license) is illegal. This is a photo and I doubt you took it. Please show that you own the right to add it under AGPL, this repositories license. If we comply with the law, we may face a take-down of the game and in rare cases legal consequences. At least, we might endanger other people who distribute the game if there is content in it that we do not own the right to distribute.

What you can do:
- Show that you own the right to distribute the file under AGPL
- Use some technique to manipulate the image that it can not be traced back e.g. roto-scoping

What do you think?

**Comment by samyakbvs** [comment]
@niccokunzmann I had no idea that we can't take the character from the internet as I didn't read the requirements of the task properly I am sorry will open another PR in sometime

**Pull request closed without merging**
