### PR TITLE
add bot

### LINKED ISSUE #913: Feature Requests : Enhance the bot
## Expected Behavior
- A handy bot to notify on gitter channel whenever a new issue/PR is made to the game. 

## Current Behavior
- The bot is a single statement which resides in deploy.sh and doesn't post messages when someone sends a pull request as it relies on auth token, which not every contributor has. Many new features can be added too.

## Possible Solution
- Propose New Features for the Bot
- Fix the current issue (bot doesn't send messages when the variables **$ROOM** and **$TOKEN** are not defined in Travis by the user) :: Workaround / Alternate method can be considered a new feature too.

### PR DESCRIPTION
**Pull request by pythongiant**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Tried to [squash the commits][squash].
- [ ] Added Screenshot / Path to tile to Indicate Location of Change in Game

### Changes done in this Pull Request

- https://github.com/apps/gitter-laby-bot/

- Fixes #913

### CODE REVIEW

**Comment by pythongiant** [comment]
@saarthakchats this is the best I could do. rest everything is bot generated

**Comment by pythongiant** [comment]
@iamareebjamal add the bot to the repository?

**Comment by iamareebjamal** [comment]
Where is the bot hosted?

**Comment by iamareebjamal** [comment]
Also, the bot code should not be hosted in the repo itself as it will be a generic bot capable of being used across FOSSASIA. To demonstrate the capabilities of the bot, please create a sample repo from your account containing the code of the bot and add bot to that repo and share the gitter channel link where updates are posted.

**Comment by pythongiant** [comment]
alright will do

**Comment by pythongiant** [comment]
@iamareebjamal I was hosting on heroku.

**Pull request closed without merging**
