### PR TITLE
Added music to chess mate tile

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Courtesy of https://soundbible.com
Take under these licenses
Creative Commons Attribution 3.0
Creative Commons Attribution 3.0 is one of many CC Audio types. Creative Commons Attribution 3.0 put simply means you can use this audio but you must attribute your work to this person. If the audio is from Mike Koenig then you need to give him credit somewhere. That somewhere could be in the credits, the cd cover, or a link to the sounds page from your site.

Public Domain Sounds
Public Domain Sounds are sounds that have been added to the public domain. They are owned by the public, and are 100% free. Items get added to the PD in a variety of different ways. 1.) Items older than the public domain age setting are automatically added. 2.)Thoughtful members of the audio community donate their own works for the good of others. 3.) Speeches by presidents and other political audio is usually considered public domain works.
Credits: Daniel Simons for his audio contribution to Labyrinth. 
For more info about licensing policies of sound bible this is the link: http://soundbible.com/royalty-free-sounds-1.html#creativecommonssounds
Deploy Link: http://rawgit.com/arjunpandey2003/labyrinth/master/index.html

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
@niccokunzmann i have taken sounds from sounbible.com and @saarthakchats has added the license folder in his PR. I have creddited Daniel simons in MY pr as well as a console message wjen my music plays, do I need to add a link to sound bible in the labyrinth index page

**Comment by arjunpandey2003** [comment]
PR link is not working due to some comma missing problem in gui.js

**Comment by niccokunzmann** [comment]
Thanks for finding out the license. Please add the license to a file with a .license in the end, see https://github.com/fossasia/labyrinth#how-to-add-music

No, currently, you do not have to add the license to the index file. We need to find a good way to show the license. I think, in the footer would be good. You can leave the console log but in the future, showing the license needs to be part of the music API.

**Comment by arjunpandey2003** [comment]
@niccokunzmann sure me and @samyakbvs are working on making credits.html a file showing all credits

**Pull request merged**
