### PR TITLE
[WIP] added tile properly :D 

### PR DESCRIPTION
**Pull request by Beta-King**
### When you change [things like this in brackets] please remember to delete brackets after you change it.

# This pull request is related to issue(s), 

# The problem(s) I want to solve or The facilitie(s) I want to improve is/are,
[Mention the bug/facilitie solved/improved]

### My steps to solve it,
[Mention the files changed. Add what changes you have done.] 

### Screenshots,
[If any]

### Links

http://rawgit.com/Beta-King/labyrinth/master/index.html

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@Beta-King Cool, the ground seems to work. You can let this pull request open and add more to it. 
The way to mark unfinished work is to add [WIP] in the title = work in progress. I will do that and have a look at your progess. Feel free to drop a comment if you have a question or like to get some feedback!

**Comment by Beta-King** [comment]
Is everything alright with the changes i've made ??

**Comment by Beta-King** [comment]
Yup it is :D

**Comment by niccokunzmann** [comment]
Looks good! Wow, golden. Thanks!

**Comment by niccokunzmann** [comment]
#261

**Comment by Beta-King** [comment]
Thank you :D

**Pull request merged**
