### PR TITLE
Added a character

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Adding a new character

My steps to solve it:
Changes: Added svg file, upadted gui.js

http://rawgit.com/arjunpandey2003/labyrinth/master/index.html

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
@abishekvashok done

**Comment by arjunpandey2003** [comment]
can you tell me why my character is so small

**Comment by abishekvashok** [comment]
@arjunpandey2003 it is such that to match the labyrinth size. We can't have a character which is larger than or having half the size of labyrinth.

**Comment by arjunpandey2003** [comment]
@abishekvashok but its hardly visible, your robo.svg is visible

**Comment by arjunpandey2003** [comment]
Making another PR

**Pull request closed without merging**
