### PR TITLE
change heading

### PR DESCRIPTION
**Pull request by niccokunzmann**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

### Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link**
  
  http://rawgit.com/USERNAME/labyrinth/master/index.html
- 
  Fixes #[Add issue number here]

### The problem I want to solve or the facility I want to improve is/are

heading was broken: markdown not recognizes

### My steps to solve it

- remove heading
- make logo bigger

### CODE REVIEW

**Comment by STEdirisuriya** [comment]
kindly please give me 1-2 hour, please don't merge this before https://github.com/fossasia/labyrinth/pull/498 . there are lot of file change in that . and please don't make conflicts

**Comment by niccokunzmann** [comment]
@STEdirisuriya Please have a look, I just change the README file. You did not change this, so there is no merge conflict. https://github.com/fossasia/labyrinth/pull/499/files

**Comment by STEdirisuriya** [comment]
@niccokunzmann I am going to change it

**Comment by niccokunzmann** [comment]
@STEdirisuriya I will merge on a approving review. If we want to block files, we can use SVN. If our workflow requires blocking, we should change the software. You can change the README in a new pull request. Also: If you do not change the lines before and after the lines I changed, there will be no merge conflict.

**Pull request merged**
